// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class Auth_Router
{
    /// <summary>
    /// 英數字，前端顯示不在網址，如：Todo
    /// </summary>
    public string RouterId { get; set; } = null!;

    /// <summary>
    /// 中文，前端顯示SideBar頁面名稱
    /// </summary>
    public string RouterName { get; set; } = null!;

    /// <summary>
    /// 給前端串接參數使用，如：/Todo/1 或 /Todo?params=
    /// </summary>
    public string? DynamicParams { get; set; }

    /// <summary>
    /// Y/N
    /// </summary>
    public string IsActive { get; set; } = null!;

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; } = null!;

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string? UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }

    /// <summary>
    /// 關聯Auth_RouterCategory
    /// </summary>
    public string RouterCategoryId { get; set; } = null!;

    /// <summary>
    /// 用於裝飾前端網頁
    /// </summary>
    public string? Icon { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    public int Sort { get; set; }
}
