// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

/// <summary>
/// 強制派案案件狀態角色設定
/// </summary>
public partial class Auth_ObligedAssignmentCardStatus_Role
{
    /// <summary>
    /// PK
    /// 自增
    /// </summary>
    public int SeqNo { get; set; }

    /// <summary>
    /// 卡片狀態
    /// </summary>
    public CardStatus CardStatus { get; set; }

    /// <summary>
    /// 角色
    /// 字串串接&apos;,&apos;
    /// </summary>
    public string? RoleId { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string? UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }
}
