// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

/// <summary>
/// 徵審權限
/// </summary>
public partial class Auth_ReviewerPermission
{
    /// <summary>
    /// PK
    /// 自增
    /// </summary>
    public int SeqNo { get; set; }

    /// <summary>
    /// 案件狀態
    /// PK
    /// </summary>
    public CardStatus CardStatus { get; set; }

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; } = null!;

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 月收入確認_是否顯示變更案件種類
    /// Y / N
    /// </summary>
    public string MonthlyIncome_IsShowChangeCaseType { get; set; } = null!;

    /// <summary>
    /// 月收入確認_是否顯示變更卡別僅國旅卡
    /// Y / N
    /// </summary>
    public string MonthlyIncome_IsShowChangeCardTypeOnlyNationalTourismCard { get; set; } = null!;

    /// <summary>
    /// 月收入確認_是否顯示權限內
    /// Y / N
    /// </summary>
    public string MonthlyIncome_IsShowInPermission { get; set; } = null!;

    /// <summary>
    /// 月收入確認_是否顯示月收入確認
    /// Y / N
    /// </summary>
    public string MonthlyIncome_IsShowMonthlyIncome { get; set; } = null!;

    /// <summary>
    /// 姓名檢核
    /// Y / N
    /// </summary>
    public string IsShowNameCheck { get; set; } = null!;

    /// <summary>
    /// 更新正卡人基本資料
    /// Y / N
    /// </summary>
    public string IsShowUpdatePrimaryInfo { get; set; } = null!;

    /// <summary>
    /// 查詢分行資訊
    /// Y / N
    /// </summary>
    public string IsShowQueryBranchInfo { get; set; } = null!;

    /// <summary>
    /// 查詢929
    /// Y / N
    /// </summary>
    public string IsShowQuery929 { get; set; } = null!;

    /// <summary>
    /// 新增圖檔
    /// Y / N
    /// </summary>
    public string IsShowInsertFileAttachment { get; set; } = null!;

    /// <summary>
    /// 編輯附件備註_備註資料
    /// Y / N
    /// </summary>
    public string IsShowUpdateApplyNote { get; set; } = null!;

    /// <summary>
    /// 修正員工
    /// </summary>
    public string? UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }

    /// <summary>
    /// 是否為當前經辦
    /// Y / N
    /// </summary>
    public string IsCurrentHandleUserId { get; set; } = null!;

    /// <summary>
    /// 新增照會摘要
    /// Y / N
    /// </summary>
    public string InsertReviewerSummary { get; set; } = null!;

    /// <summary>
    /// 再查詢關注名單1
    /// Y / N
    /// </summary>
    public string IsShowFocus1 { get; set; } = null!;

    /// <summary>
    /// 再查詢關注名單2
    /// Y / N
    /// </summary>
    public string IsShowFocus2 { get; set; } = null!;

    /// <summary>
    /// 再查詢 檢驗手機號碼相同
    /// Y / N
    /// </summary>
    public string IsShowWebMobileRequery { get; set; } = null!;

    /// <summary>
    /// 再查詢 檢驗電子信箱相同
    /// Y / N
    /// </summary>
    public string IsShowWebEmailRequery { get; set; } = null!;

    /// <summary>
    /// 徵審照會摘要-編輯
    /// Y / N
    /// </summary>
    public string IsShowUpdateReviewerSummary { get; set; } = null!;

    /// <summary>
    /// 徵審照會摘要-刪除
    /// Y / N
    /// </summary>
    public string IsShowDeleteReviewerSummary { get; set; } = null!;

    /// <summary>
    /// 圖檔刪除
    /// Y / N
    /// </summary>
    public string IsShowDeleteApplyFileAttachment { get; set; } = null!;

    /// <summary>
    /// 溝通備註
    /// Y / N
    /// </summary>
    public string IsShowCommunicationNotes { get; set; } = null!;

    /// <summary>
    /// 卡片階段
    /// 1.月收入確認
    /// 2.人工徵審
    /// 主因原廠商的有些狀態有重疊導致但權限跟流程又要不同,例如補件作業中,人工徵信的補件作業件要把狀態改為補回件
    /// 
    /// </summary>
    public CardStep? CardStep { get; set; }

    /// <summary>
    /// 人工徵審_是否顯示變更案件種類
    /// Y / N
    /// </summary>
    public string ManualReview_IsShowChangeCaseType { get; set; } = null!;

    /// <summary>
    /// 人工徵審_是否顯示權限內
    /// Y / N
    /// </summary>
    public string ManualReview_IsShowInPermission { get; set; } = null!;

    /// <summary>
    /// 人工徵審_是否顯示權限外
    /// Y / N
    /// </summary>
    public string ManualReview_IsShowOutPermission { get; set; } = null!;

    /// <summary>
    /// 人工徵審_是否顯示退回重審
    /// Y / N
    /// </summary>
    public string ManualReview_IsShowReturnReview { get; set; } = null!;

    /// <summary>
    /// 儲存相同 IP確認紀錄
    /// Y / N
    /// </summary>
    public string IsShowUpdateSameIPCheckRecord { get; set; } = null!;

    /// <summary>
    /// 儲存網路手機號碼確認紀錄
    /// Y / N
    /// </summary>
    public string IsShowUpdateWebMobileCheckRecord { get; set; } = null!;

    /// <summary>
    /// 儲存網路電子信箱確認紀錄
    /// Y / N
    /// </summary>
    public string IsShowUpdateWebEmailCheckRecord { get; set; } = null!;

    /// <summary>
    /// 儲存行內 IP確認紀錄
    /// Y / N
    /// </summary>
    public string IsShowUpdateInternalIPCheckRecord { get; set; } = null!;

    /// <summary>
    /// 儲存短時間頻繁確認紀錄
    /// Y / N
    /// </summary>
    public string IsShowUpdateShortTimeIDCheckRecord { get; set; } = null!;

    /// <summary>
    /// 再查詢行內手機
    /// Y / N
    /// </summary>
    public string IsShowInternalMobile { get; set; } = null!;

    /// <summary>
    /// 再查詢行內Email
    /// Y / N
    /// </summary>
    public string IsShowInternalEmail { get; set; } = null!;

    /// <summary>
    /// 儲存行內手機確認紀錄
    /// Y / N
    /// </summary>
    public string IsShowUpdateInternalMobileCheckRecord { get; set; } = null!;

    /// <summary>
    /// 儲存行內Email確認紀錄
    /// Y / N
    /// </summary>
    public string IsShowUpdateInternalEmailCheckRecord { get; set; } = null!;

    /// <summary>
    /// 更新附卡人基本資料
    /// Y/ N
    /// </summary>
    public string IsShowUpdateSupplementaryInfo { get; set; } = null!;

    /// <summary>
    /// KYC入檔
    /// Y / N
    /// 在人工徵信中顯示
    /// </summary>
    public string IsShowKYCSync { get; set; } = null!;
}
