// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

/// <summary>
/// 使用者
/// </summary>
public partial class OrgSetUp_User
{
    /// <summary>
    /// 使用者帳號
    /// </summary>
    public string UserId { get; set; } = null!;

    /// <summary>
    /// 是否啟用，Y | N
    /// </summary>
    public string IsActive { get; set; } = null!;

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; } = null!;

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string? UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }

    /// <summary>
    /// 使用者姓名
    /// </summary>
    public string UserName { get; set; } = null!;

    /// <summary>
    /// 是否AD
    /// </summary>
    public string IsAD { get; set; } = null!;

    /// <summary>
    /// 密碼
    /// </summary>
    public string? Mima { get; set; }

    /// <summary>
    /// 最後變更密碼時間
    /// </summary>
    public DateTime? LastUpdateMimaTime { get; set; }

    /// <summary>
    /// 組織代碼
    /// 1. 關聯 OrgSetUp_Organize
    /// 2.跟派案組織無關
    /// </summary>
    public string? OrganizeCode { get; set; }

    /// <summary>
    /// 停用原因，IsActive = N 需有值
    /// </summary>
    public string? StopReason { get; set; }

    /// <summary>
    /// 密碼錯誤次數
    /// 1. 預設 0
    /// 2. 達 5 次 IsActive = N，StopReason　= 密碼輸入超過5次
    /// </summary>
    public int MimaErrorCount { get; set; }

    /// <summary>
    /// 派案群組
    /// 用於整批派案
    /// </summary>
    public string? CaseDispatchGroup { get; set; }

    /// <summary>
    /// 員工編號
    /// </summary>
    public string? EmployeeNo { get; set; }
}
