// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class Report_BatchReportDownload
{
    /// <summary>
    /// PK
    /// </summary>
    public string SeqNo { get; set; } = null!;

    /// <summary>
    /// 報表名稱
    /// </summary>
    public string ReportName { get; set; } = null!;

    /// <summary>
    /// 報表類型
    /// </summary>
    public ReportType ReportType { get; set; }

    /// <summary>
    /// 報表完整地址
    /// </summary>
    public string ReportFullAddr { get; set; } = null!;

    /// <summary>
    /// 新增日期
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 最後下載人員
    /// </summary>
    public string? LastDownloadUserId { get; set; }
}
