// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class Reviewer_ApplyCreditCardInfoSupplementary
{
    /// <summary>
    /// 申請書編號
    /// PK
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 中文姓名
    /// </summary>
    public string CHName { get; set; } = null!;

    /// <summary>
    /// 身分證字號
    /// PK
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 性別
    /// 1 = 男
    /// 2 = 女 
    /// </summary>
    public Sex? Sex { get; set; }

    /// <summary>
    /// 出生年月日
    /// 目前系統是請他提供YYYMMDD
    /// </summary>
    public string? BirthDay { get; set; }

    /// <summary>
    /// 英文姓名
    /// </summary>
    public string? ENName { get; set; }

    /// <summary>
    /// 婚姻狀況
    /// 1.已婚
    /// 2.未婚
    /// 3.其他
    /// </summary>
    public MarriageState? MarriageState { get; set; }

    /// <summary>
    /// 與正卡人關係
    /// 1. 配偶
    /// 2. 父母
    /// 3. 子女
    /// 4. 兄弟姊妹
    /// 7. 配偶父母
    /// </summary>
    public ApplicantRelationship? ApplicantRelationship { get; set; }

    /// <summary>
    /// 國籍
    /// 由徵審系統提供值給E-CARD
    /// 關聯 SetUp_Citizenship
    /// </summary>
    public string? CitizenshipCode { get; set; }

    /// <summary>
    /// 身分證發證日期
    /// 民國YYYMMDD
    /// </summary>
    public string? IDIssueDate { get; set; }

    /// <summary>
    /// 身分證發證地點
    /// 關聯 SetUp_IDCardRenewalLocation
    /// </summary>
    public string? IDCardRenewalLocationCode { get; set; }

    /// <summary>
    /// 身分證請領狀態
    /// 1.初發
    /// 2.補發
    /// 3.換發
    /// </summary>
    public IDTakeStatus? IDTakeStatus { get; set; }

    /// <summary>
    /// 出生地國籍
    /// 1. 中華民國
    /// 2. 其他
    /// </summary>
    public BirthCitizenshipCode? BirthCitizenshipCode { get; set; }

    /// <summary>
    /// 是否FATCA身份
    /// Y/N
    /// </summary>
    public string? IsFATCAIdentity { get; set; }

    /// <summary>
    /// 社會安全碼
    /// FATCA身份=Y，徵審人員會去跟客人要此值
    /// </summary>
    public string? SocialSecurityCode { get; set; }

    /// <summary>
    /// 是否為永久居留證
    /// 配合法遵部政策，新增欄位。
    /// 欄位用拉霸方式選擇，Y/N，預設為N。
    /// 如為{N}，則須鍵入外籍人士指定效期。
    /// 
    /// </summary>
    public string? IsForeverResidencePermit { get; set; }

    /// <summary>
    /// 居留證發證日期 
    /// YYYYMMDD
    /// </summary>
    public string? ResidencePermitIssueDate { get; set; }

    /// <summary>
    /// 居留證期限
    /// 格式 YYYYMMDD
    /// </summary>
    public string? ResidencePermitDeadline { get; set; }

    /// <summary>
    /// 居留證背面號碼
    /// 前兩碼大寫英文 + 8 碼數字，範例ＹＺ80000001
    /// </summary>
    public string? ResidencePermitBackendNum { get; set; }

    /// <summary>
    /// 護照號碼
    /// </summary>
    public string? PassportNo { get; set; }

    /// <summary>
    /// 護照日期
    /// YYYYMMDD
    /// </summary>
    public string? PassportDate { get; set; }

    /// <summary>
    /// 外籍人士指定效期
    /// YYYYMM
    /// </summary>
    public string? ExpatValidityPeriod { get; set; }

    /// <summary>
    /// 舊照查驗
    /// Y：是、N：否
    /// </summary>
    public string? OldCertificateVerified { get; set; }

    /// <summary>
    /// 公司名稱
    /// </summary>
    public string? CompName { get; set; }

    /// <summary>
    /// 職稱
    /// </summary>
    public string? CompJobTitle { get; set; }

    /// <summary>
    /// 公司電話
    /// 範例020-28572463#55555，3碼-七八碼#多碼分機
    /// </summary>
    public string? CompPhone { get; set; }

    /// <summary>
    /// 居住電話
    /// 範例020-28572463
    /// 3碼-七八碼
    /// </summary>
    public string? LivePhone { get; set; }

    /// <summary>
    /// 行動電話
    /// </summary>
    public string? Mobile { get; set; }

    /// <summary>
    /// 居住_郵遞區號
    /// </summary>
    public string? Live_ZipCode { get; set; }

    /// <summary>
    /// 居住_縣市
    /// </summary>
    public string? Live_City { get; set; }

    /// <summary>
    /// 居住_區域
    /// </summary>
    public string? Live_District { get; set; }

    /// <summary>
    /// 居住_街道
    /// </summary>
    public string? Live_Road { get; set; }

    /// <summary>
    /// 居住_巷
    /// </summary>
    public string? Live_Lane { get; set; }

    /// <summary>
    /// 居住_弄
    /// </summary>
    public string? Live_Alley { get; set; }

    /// <summary>
    /// 居住_號
    /// </summary>
    public string? Live_Number { get; set; }

    /// <summary>
    /// 居住_之號
    /// </summary>
    public string? Live_SubNumber { get; set; }

    /// <summary>
    /// 居住_樓層
    /// </summary>
    public string? Live_Floor { get; set; }

    /// <summary>
    /// 居住_完整地址
    /// </summary>
    public string? Live_FullAddr { get; set; }

    /// <summary>
    /// 居住_其他
    /// </summary>
    public string? Live_Other { get; set; }

    /// <summary>
    /// 寄卡_郵遞區號
    /// </summary>
    public string? SendCard_ZipCode { get; set; }

    /// <summary>
    /// 寄卡_縣市
    /// </summary>
    public string? SendCard_City { get; set; }

    /// <summary>
    /// 寄卡_區域
    /// </summary>
    public string? SendCard_District { get; set; }

    /// <summary>
    /// 寄卡_街道
    /// </summary>
    public string? SendCard_Road { get; set; }

    /// <summary>
    /// 寄卡_巷
    /// </summary>
    public string? SendCard_Lane { get; set; }

    /// <summary>
    /// 寄卡_弄
    /// </summary>
    public string? SendCard_Alley { get; set; }

    /// <summary>
    /// 寄卡_號
    /// </summary>
    public string? SendCard_Number { get; set; }

    /// <summary>
    /// 寄卡_之號
    /// </summary>
    public string? SendCard_SubNumber { get; set; }

    /// <summary>
    /// 寄卡_樓層
    /// </summary>
    public string? SendCard_Floor { get; set; }

    /// <summary>
    /// 寄卡_完整地址
    /// </summary>
    public string? SendCard_FullAddr { get; set; }

    /// <summary>
    /// 寄卡_其他
    /// </summary>
    public string? SendCard_Other { get; set; }

    /// <summary>
    /// 敦陽系統黑名單是否相符 
    /// Y：是、N：否
    /// 由行員確認
    /// </summary>
    public string? IsDunyangBlackList { get; set; }

    /// <summary>
    /// 姓名檢核理由代碼
    /// 可為複數以「,」分割，姓名檢核 = Y 要有理由碼
    /// 1. PEP
    /// 2. 要再問
    /// 3. 黑名單
    /// 4. 負面新聞
    /// 5. 無
    /// 6. RCA
    /// 7. 國內PEP
    /// 8. 國外PEP
    /// 9. 國際組織PEP
    /// 10. 卸任PEP
    /// </summary>
    public string? NameCheckedReasonCodes { get; set; }

    /// <summary>
    /// 使用者類型
    /// PK
    /// 固定 2 = 附卡人
    /// </summary>
    public UserType UserType { get; set; }

    /// <summary>
    /// 是否原持卡人
    /// - Y:是/N:否
    /// - 查詢 MW3 原持卡人如有資料則為Y則為原持卡人
    /// </summary>
    public string? IsOriginalCardholder { get; set; }

    /// <summary>
    /// 是否重複申請件
    /// - Y:是/N:否
    /// - 查詢 MW3 原持卡人如有資料則為Y且徵審系統有資料則為重複進件
    /// 
    /// </summary>
    public string? IsRepeatApply { get; set; }

    /// <summary>
    /// 出生地其他
    /// BirthCitizenshipCode = 2(其他)為必填
    /// 關聯 SetUp_Citizenship
    /// </summary>
    public string? BirthCitizenshipCodeOther { get; set; }

    /// <summary>
    /// 居住地址類型
    /// 同正卡居住地址 = 1
    /// 其他 = 2
    /// 主要用於前端顯示
    /// </summary>
    public ResidenceType? ResidenceType { get; set; }

    /// <summary>
    /// 寄卡地址類型
    /// 同正卡寄卡地址 = 1
    /// 親領 = 2
    /// 主要用於前端顯示
    /// </summary>
    public ShippingCardAddressType? ShippingCardAddressType { get; set; }

    /// <summary>
    /// 當前或曾為PEP身分 (Y/N)，敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 需填寫
    /// </summary>
    public string? ISRCAForCurrentPEP { get; set; }

    /// <summary>
    /// 卸任PEP種類：1. 國內 2.國外 3.國際組織 / 敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 需填寫
    /// </summary>
    public ResignPEPKind? ResignPEPKind { get; set; }

    /// <summary>
    /// 擔任PEP範圍:
    /// 不滿2年
    /// 滿兩年但不滿四年
    /// 滿4年 / 敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 需填寫
    /// </summary>
    public PEPRange? PEPRange { get; set; }

    /// <summary>
    /// 現任職位是否與PEP職位相關 (Y/N)，敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 需填寫
    /// </summary>
    public string? IsCurrentPositionRelatedPEPPosition { get; set; }

    /// <summary>
    /// 姓名檢核
    /// 
    /// - 敦陽系統之姓名檢核
    /// - Y 、N
    /// </summary>
    public string? NameChecked { get; set; }
}
