// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

/// <summary>
/// 徵審_行內Email相同Log
/// </summary>
public partial class Reviewer_BankInternalSameLog
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// FK
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 使用者類型
    /// </summary>
    public UserType UserType { get; set; }

    /// <summary>
    /// 同EmailID
    /// </summary>
    public string SameID { get; set; } = null!;

    /// <summary>
    /// 同Email姓名
    /// </summary>
    public string SameName { get; set; } = null!;

    /// <summary>
    /// 檢驗類型
    /// 
    /// 1. Email
    /// 2. Mobile
    /// </summary>
    public BankInternalSameCheckType CheckType { get; set; }

    /// <summary>
    /// 同帳單地址
    /// </summary>
    public string? SameBillAddr { get; set; }
}
