// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class Reviewer3rd_BranchCusCAD
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 分行代碼
    /// </summary>
    public string Cate { get; set; } = null!;

    /// <summary>
    /// 帳戶別
    /// </summary>
    public string Account { get; set; } = null!;

    /// <summary>
    /// 開戶日
    /// 
    /// 範例: 01000101
    /// </summary>
    public string OpenAccountD { get; set; } = null!;

    /// <summary>
    /// 目前餘額基準日
    /// 
    /// 範例: 01000101
    /// </summary>
    public string CreditD { get; set; } = null!;

    /// <summary>
    /// 近三個月平均餘額
    /// </summary>
    public int Last3MavgCredit { get; set; }

    /// <summary>
    /// 三個月平均餘額
    /// </summary>
    public int ThreeMavgCredit { get; set; }

    /// <summary>
    /// 兩個月平均餘額
    /// </summary>
    public int TwoMavgCredit { get; set; }

    /// <summary>
    /// 一個月平均餘額
    /// </summary>
    public int OneMavgCredit { get; set; }

    /// <summary>
    /// 目前餘額
    /// </summary>
    public int Credit { get; set; }

    /// <summary>
    /// 使用者類型
    /// 1. 正卡人
    /// 2. 附卡人
    /// </summary>
    public UserType UserType { get; set; }
}
