// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

/// <summary>
/// 聯徵資料-收容遣返Log
/// </summary>
public partial class Reviewer3rd_PunishLog
{
    /// <summary>
    /// PK，自增
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 統一證號
    /// </summary>
    public string? ResidentIdNo { get; set; }

    /// <summary>
    /// 英文姓名
    /// </summary>
    public string? ENName { get; set; }

    /// <summary>
    /// 護照號碼
    /// </summary>
    public string? PassportNo { get; set; }

    /// <summary>
    /// 國籍
    /// 菲律賓 24、印尼 9、泰國 30、越南 34、馬來西亞 19、蒙古 21，前方不補 0
    /// </summary>
    public string? Nationality { get; set; }

    /// <summary>
    /// 出生日期
    /// </summary>
    public string? BirthDate { get; set; }

    /// <summary>
    /// 性別
    /// 0:男性，1:女性，可能為空值
    /// </summary>
    public string? Gender { get; set; }

    /// <summary>
    /// 查獲日期
    /// </summary>
    public string? CatchingDate { get; set; }

    /// <summary>
    /// 出境日期
    /// </summary>
    public string? ImmigrateDate { get; set; }

    /// <summary>
    /// 資料更新日期
    /// </summary>
    public string? CreateDate { get; set; }

    /// <summary>
    /// 使用者類型
    /// 1. 正卡人
    /// 2. 附卡人
    /// </summary>
    public UserType UserType { get; set; }

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;
}
