// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class Reviewer_CardHolderChangeLog
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 類型
    /// 
    /// 1. 正卡人
    /// 2. 附卡人
    /// </summary>
    public UserType UserType { get; set; }

    /// <summary>
    /// 附卡人ID
    /// </summary>
    public string? SupplementaryID { get; set; }

    /// <summary>
    /// 變更時間
    /// </summary>
    public DateTime ChangeDateTime { get; set; }

    /// <summary>
    /// 變更人員編號
    /// </summary>
    public string ChangeUserId { get; set; } = null!;

    /// <summary>
    /// 變更人員姓名
    /// </summary>
    public string? ChangeUserName { get; set; }

    /// <summary>
    /// 變更來源 
    /// 
    ///  • API
    ///  • Batch
    ///  • Middleware
    ///  • PaperMiddleware
    /// </summary>
    public string? ChangeSource { get; set; }

    /// <summary>
    /// 變更 API 端點路徑
    /// </summary>
    public string? ChangeAPIEndpoint { get; set; }

    /// <summary>
    /// 變更前完整資料 
    /// 
    /// JSON 格式,備查用
    /// </summary>
    public string? BeforeData { get; set; }

    /// <summary>
    /// 變更後完整資料
    /// 
    /// JSON 格式,備查用
    /// </summary>
    public string? AfterData { get; set; }

    /// <summary>
    /// 異動欄位清單 
    /// 
    /// 逗號分隔,例如: CHName,Mobile,EMail
    /// </summary>
    public string? ChangedFields { get; set; }

    /// <summary>
    /// 操作來源 IP 位置 
    /// </summary>
    public string? IpAddress { get; set; }

    /// <summary>
    /// 變更前行動電話 
    /// 
    /// 報表專用欄位
    /// </summary>
    public string? BeforeMobile { get; set; }

    /// <summary>
    /// 變更後行動電話
    /// 
    /// 報表專用欄位
    /// </summary>
    public string? AfterMobile { get; set; }

    /// <summary>
    /// 變更前 Email
    /// 
    /// 報表專用欄位
    /// </summary>
    public string? BeforeEmail { get; set; }

    /// <summary>
    /// 變更後 Email
    /// 
    /// 報表專用欄位
    /// </summary>
    public string? AfterEmail { get; set; }

    /// <summary>
    /// 變更前帳單地址
    /// 
    /// 報表專用欄位
    /// </summary>
    public string? BeforeBillAddress { get; set; }

    /// <summary>
    /// 變更後帳單地址
    /// 
    /// 報表專用欄位
    /// </summary>
    public string? AfterBillAddress { get; set; }

    /// <summary>
    /// 變更前寄卡地址
    /// 
    /// 報表專用欄位
    /// </summary>
    public string? BeforeSendCardAddress { get; set; }

    /// <summary>
    /// 變更後寄卡地址
    /// 
    /// 報表專用欄位
    /// </summary>
    public string? AfterSendCardAddress { get; set; }

    /// <summary>
    /// 備註說明
    /// </summary>
    public string? Remark { get; set; }
}
