// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class Reviewer_CaseStatistics
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 員工編號
    /// </summary>
    public string UserId { get; set; } = null!;

    /// <summary>
    /// 新增日期
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 類型
    /// 
    /// 1. 系統派案
    /// 2. 整批派案
    /// 3. 調撥案件
    /// 4. 強制派案
    /// 5. 待派案-人工
    /// 6. 調撥-人工
    /// </summary>
    public CaseStatisticType CaseType { get; set; }

    /// <summary>
    /// 案件編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;
}
