// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class Reviewer3rd_WarnLog
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 資料類型
    /// </summary>
    public string? DataType { get; set; }

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string? ID { get; set; }

    /// <summary>
    /// 告誡日期
    /// </summary>
    public string? WarningDate { get; set; }

    /// <summary>
    /// 告誡期限
    /// </summary>
    public string? ExpireDate { get; set; }

    /// <summary>
    /// 告誡分局
    /// </summary>
    public string? Issuer { get; set; }

    /// <summary>
    /// 資料匯入日
    /// </summary>
    public string? CreateDate { get; set; }

    /// <summary>
    /// 使用者類型
    /// 1. 正卡人
    /// 2. 附卡人
    /// </summary>
    public UserType UserType { get; set; }
}
