// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class Reviewer3rd_NameCheckLog
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 使用者類型
    /// 
    /// 1. 正卡人
    /// 2. 附卡人
    /// </summary>
    public UserType UserType { get; set; }

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 開始時間
    /// </summary>
    public DateTime StartTime { get; set; }

    /// <summary>
    /// 結束時間
    /// </summary>
    public DateTime EndTime { get; set; }

    /// <summary>
    /// 回覆結果
    /// 
    /// 
    /// Y | N
    /// </summary>
    public string ResponseResult { get; set; } = null!;

    /// <summary>
    /// RC分數
    /// </summary>
    public int RcPoint { get; set; }

    /// <summary>
    /// AML系統鍵值
    /// </summary>
    public string AMLId { get; set; } = null!;

    /// <summary>
    /// 自訂交易序號
    /// </summary>
    public string TraceId { get; set; } = null!;

    /// <summary>
    /// 姓名
    /// </summary>
    public string Name { get; set; } = null!;
}
