// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

/// <summary>
/// 申請書附件
/// </summary>
public partial class Reviewer_ApplyFileAttachment
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 使用者類型
    /// 1.正卡人
    /// 2.附卡人
    /// </summary>
    public UserType UserType { get; set; }

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; } = null!;

    /// <summary>
    /// 刪除時間
    /// </summary>
    public DateTime? DeleteTime { get; set; }

    /// <summary>
    /// 刪除員工
    /// </summary>
    public string? DeleteUserId { get; set; }

    /// <summary>
    /// 檔案 GUID
    /// 
    /// 關聯Reviewer_ApplyFile
    /// </summary>
    public Guid FileId { get; set; }

    /// <summary>
    /// 資料庫檔案名稱
    /// </summary>
    public string DBName { get; set; } = null!;

    /// <summary>
    /// Y/N，預設N
    /// </summary>
    public string IsHistory { get; set; } = null!;
}
