// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

/// <summary>
/// 徵審_金融檢核
/// </summary>
public partial class Reviewer_FinanceCheckInfo
{
    /// <summary>
    /// 申請書編號
    /// 
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 使用者類型
    /// 1 = 正卡人 
    /// 2 =  附卡人
    /// </summary>
    public UserType UserType { get; set; }

    /// <summary>
    /// 身分證查驗結果
    /// 
    /// - 資料來源總行業管部自建資料庫
    /// - Y 、N
    /// </summary>
    public string? IDCheckResultChecked { get; set; }

    /// <summary>
    /// 家事法訊息
    /// 
    /// - 資料來源總行業管部自建資料庫
    /// - Y 、N
    /// </summary>
    public string? FamilyMessageChecked { get; set; }

    /// <summary>
    /// 929檢核
    /// 
    /// - 用API方式以身分證字號查詢資料庫，檢核是否命中情形，資料庫來源為業務管理部
    /// - 入月收入確認前會先發查一次
    /// - 完成月收入確認時，如與落月收入確認發查日非為同一天，會再發查一次
    /// - 核卡的日期，如前一次發查929的日期非同一日，會再次發查。
    /// 
    /// 
    /// </summary>
    public string? Checked929 { get; set; }

    /// <summary>
    /// 是否為分行客戶
    /// 
    /// - Y / N
    /// </summary>
    public string? IsBranchCustomer { get; set; }

    /// <summary>
    /// 關注名單1
    /// 
    /// - Y/N
    /// </summary>
    public string? Focus1Check { get; set; }

    /// <summary>
    /// 命中關注名單1
    /// 
    /// - 命中的話會以代號串接使用、分割
    /// </summary>
    public string? Focus1Hit { get; set; }

    /// <summary>
    /// 關注名單2
    /// 
    /// - Y/N
    /// </summary>
    public string? Focus2Check { get; set; }

    /// <summary>
    /// 命中關注名單2
    /// 
    /// - 命中的話會以代號串接使用、分割
    /// </summary>
    public string? Focus2Hit { get; set; }

    /// <summary>
    /// 929_回傳代碼
    /// </summary>
    public string? Q929_RtnCode { get; set; }

    /// <summary>
    /// 929_回傳訊息
    /// </summary>
    public string? Q929_RtnMsg { get; set; }

    /// <summary>
    /// 929_查詢時間
    /// </summary>
    public DateTime? Q929_QueryTime { get; set; }

    /// <summary>
    /// 分行客戶_回傳代碼
    /// </summary>
    public string? BranchCus_RtnCode { get; set; }

    /// <summary>
    /// 分行客戶_回傳訊息
    /// </summary>
    public string? BranchCus_RtnMsg { get; set; }

    /// <summary>
    /// 分行客戶_查詢時間
    /// </summary>
    public DateTime? BranchCus_QueryTime { get; set; }

    /// <summary>
    /// 關注名單1_回傳代碼
    /// </summary>
    public string? Focus1_RtnCode { get; set; }

    /// <summary>
    /// 關注名單1_回傳訊息
    /// </summary>
    public string? Focus1_RtnMsg { get; set; }

    /// <summary>
    /// 關注名單1_查詢時間
    /// </summary>
    public DateTime? Focus1_QueryTime { get; set; }

    /// <summary>
    /// 關注名單1_TraceId
    /// </summary>
    public string? Focus1_TraceId { get; set; }

    /// <summary>
    /// 關注名單2_回傳代碼
    /// </summary>
    public string? Focus2_RtnCode { get; set; }

    /// <summary>
    /// 關注名單2_回傳訊息
    /// </summary>
    public string? Focus2_RtnMsg { get; set; }

    /// <summary>
    /// 關注名單2_查詢時間
    /// </summary>
    public DateTime? Focus2_QueryTime { get; set; }

    /// <summary>
    /// 關注名單2_TraceId
    /// </summary>
    public string? Focus2_TraceId { get; set; }

    /// <summary>
    /// 洗防風險等級
    /// </summary>
    public string? AMLRiskLevel { get; set; }

    /// <summary>
    /// KYC_回傳代碼
    /// </summary>
    public string? KYC_RtnCode { get; set; }

    /// <summary>
    /// KYC_查詢時間
    /// </summary>
    public DateTime? KYC_QueryTime { get; set; }

    /// <summary>
    /// KYC 回傳訊息
    /// </summary>
    public string? KYC_Message { get; set; }

    /// <summary>
    /// KYC加強審核版本
    /// 
    /// - 利用此欄位決定KYC加強審核版本主要用於套印加強審核檔案
    /// - 由系統參數決定
    /// </summary>
    public string? KYC_StrongReVersion { get; set; }

    /// <summary>
    /// 加強審核執行狀態
    /// 
    /// - 狀態為 不需檢核 或 核准,才能核卡，否則就需要做加強審核簽核才行
    /// 
    /// 定義值
    /// 1. 未送審 (經辦)
    /// 2. 送審中 (主管) 
    /// 3. 核准 (可核卡) (經辦) 
    /// 4. 駁回 (經辦) 
    /// 5. 不需檢核
    /// 
    /// </summary>
    public KYCStrongReStatus? KYC_StrongReStatus { get; set; }

    /// <summary>
    /// KYC_經辦
    /// </summary>
    public string? KYC_Handler { get; set; }

    /// <summary>
    /// KYC_經辦_簽核時間
    /// </summary>
    public DateTime? KYC_Handler_SignTime { get; set; }

    /// <summary>
    /// KYC_覆核
    /// </summary>
    public string? KYC_Reviewer { get; set; }

    /// <summary>
    /// KYC_覆核_簽核時間
    /// </summary>
    public DateTime? KYC_Reviewer_SignTime { get; set; }

    /// <summary>
    /// KYC_防洗錢主管
    /// </summary>
    public string? KYC_KYCManager { get; set; }

    /// <summary>
    /// KYC_防洗錢主管_簽核時間
    /// </summary>
    public DateTime? KYC_KYCManager_SignTime { get; set; }

    /// <summary>
    /// KYC_加強審核詳細資訊Json
    /// </summary>
    public string? KYC_StrongReDetailJson { get; set; }

    /// <summary>
    /// KYC_建議核准
    /// 
    /// - Y/N
    /// </summary>
    public string? KYC_Suggestion { get; set; }
}
