// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class Reviewer3rd_BranchCusCreditOver
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 分行授信帳號
    /// 
    /// 範例: 000000000001
    /// </summary>
    public string Account { get; set; } = null!;

    /// <summary>
    /// 逾期狀態
    /// 
    /// 範例: M1
    /// </summary>
    public string OverStatus { get; set; } = null!;

    /// <summary>
    /// 使用者類型
    /// 1. 正卡人
    /// 2. 附卡人
    /// </summary>
    public UserType UserType { get; set; }
}
