// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class Reviewer_ApplyCreditCardInfoQueryLog
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 使用者帳號
    /// </summary>
    public string UserId { get; set; } = null!;

    /// <summary>
    /// 查詢時間
    /// </summary>
    public DateTime QueryTime { get; set; }
}
