// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

/// <summary>
/// 徵審內部溝通
/// </summary>
public partial class Reviewer_InternalCommunicate
{
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 溝通註記
    /// 當核卡完成時清空
    /// </summary>
    public string? CommunicationNotes { get; set; }

    /// <summary>
    /// 補聯繫紀錄_登錄人員
    /// </summary>
    public string? SupplementContactRecords_UserId { get; set; }

    /// <summary>
    /// 補聯繫紀錄_類別
    /// </summary>
    public SupplementContactRecordsType? SupplementContactRecords_Type { get; set; }

    /// <summary>
    /// 補聯繫紀錄_結果
    /// </summary>
    public SupplementContactRecordsResult? SupplementContactRecords_Result { get; set; }

    /// <summary>
    /// 補聯繫紀錄_摘要
    /// </summary>
    public string? SupplementContactRecords_Summary { get; set; }
}
