// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class SetUp_FixTime
{
    public long SeqNo { get; set; }

    /// <summary>
    /// KYC是否維護
    /// </summary>
    public string KYC_IsFix { get; set; } = null!;

    /// <summary>
    /// KYC_開始日期
    /// 
    /// 當KYC_IsFix = Y 為必填
    /// </summary>
    public DateTime? KYC_StartTime { get; set; }

    /// <summary>
    /// KYC_結束日期
    /// 
    /// 當KYC_IsFix = Y 為必填
    /// </summary>
    public DateTime? KYC_EndTime { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string? UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }
}
