// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

/// <summary>
/// 年費收取方式設定
/// </summary>
public partial class SetUp_AnnualFeeCollectionMethod
{
    /// <summary>
    /// 年費收取代碼
    /// 範例: 1
    /// PK
    /// </summary>
    public string AnnualFeeCollectionCode { get; set; } = null!;

    /// <summary>
    /// 年費收取名稱
    /// </summary>
    public string AnnualFeeCollectionName { get; set; } = null!;

    /// <summary>
    /// 是否啟用
    /// Y | N
    /// </summary>
    public string IsActive { get; set; } = null!;

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; } = null!;

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string? UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }
}
