// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class SetUp_AddressInfo
{
    /// <summary>
    /// PK
    /// </summary>
    public string SeqNo { get; set; } = null!;

    /// <summary>
    /// 郵遞區號
    /// </summary>
    public string ZIPCode { get; set; } = null!;

    /// <summary>
    /// 縣市，例如新北市
    /// </summary>
    public string City { get; set; } = null!;

    /// <summary>
    /// 區域，例如蘆洲區
    /// </summary>
    public string Area { get; set; } = null!;

    /// <summary>
    /// 街道
    /// </summary>
    public string Road { get; set; } = null!;

    /// <summary>
    /// 號判斷郵遞區號規則
    /// </summary>
    public string Scope { get; set; } = null!;

    public string IsActive { get; set; } = null!;

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; } = null!;

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string? UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }
}
