// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class SetUp_WorkDay
{
    /// <summary>
    /// 日期
    /// </summary>
    public string Date { get; set; } = null!;

    /// <summary>
    /// 西元年分
    /// </summary>
    public string Year { get; set; } = null!;

    /// <summary>
    /// 節日
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// 是否放假
    /// Y/N
    /// </summary>
    public string IsHoliday { get; set; } = null!;

    /// <summary>
    /// 假日類別
    /// </summary>
    public string? HolidayCategory { get; set; }

    /// <summary>
    /// 備註
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; } = null!;

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string? UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }
}
