// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

/// <summary>
/// 卡片種類_優惠辦法關聯表
/// </summary>
public partial class SetUp_Card_CardPromotion
{
    /// <summary>
    /// PK
    /// </summary>
    public int SeqNo { get; set; }

    /// <summary>
    /// BINCode，範例：JST65，關聯 SetUp_Card
    /// </summary>
    public string BINCode { get; set; } = null!;

    /// <summary>
    /// 優惠辦法代碼，範例：JST65，關聯 SetUp_CardPromotion
    /// </summary>
    public string CardPromotionCode { get; set; } = null!;

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; } = null!;

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }
}
