// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

/// <summary>
/// 身分證換發地點
/// </summary>
public partial class SetUp_IDCardRenewalLocation
{
    /// <summary>
    /// 身分證換發地點代碼，範例: 09007000
    /// </summary>
    public string IDCardRenewalLocationCode { get; set; } = null!;

    /// <summary>
    /// 身分證換發地點名稱，範例: 北市
    /// </summary>
    public string IDCardRenewalLocationName { get; set; } = null!;

    /// <summary>
    /// 是否啟用，Y | N
    /// </summary>
    public string IsActive { get; set; } = null!;

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; } = null!;

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string? UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }
}
