// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

/// <summary>
/// 樣板固定值
/// </summary>
public partial class SetUp_TemplateFixContent
{
    /// <summary>
    /// PK，自增
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 樣板ID，關聯  SetUp_Template
    /// </summary>
    public string TemplateId { get; set; } = null!;

    /// <summary>
    /// Key，程式相關人員設定
    /// </summary>
    public string TemplateKey { get; set; } = null!;

    /// <summary>
    /// Value，行員可以自行設定
    /// </summary>
    public string TemplateValue { get; set; } = null!;

    /// <summary>
    /// 新增員工
    /// </summary>
    public string AddUserId { get; set; } = null!;

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 修正員工
    /// </summary>
    public string? UpdateUserId { get; set; }

    /// <summary>
    /// 修正時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }

    /// <summary>
    /// 是否啟用，Y | N
    /// </summary>
    public string IsActive { get; set; } = null!;
}
