// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

/// <summary>
/// 排程設定
/// </summary>
public partial class SysParamManage_BatchSet
{
    /// <summary>
    /// PK
    /// </summary>
    public int SeqNo { get; set; }

    /// <summary>
    /// 網路件申請書檔案異常重新抓取_是否啟動
    /// Y / N
    /// </summary>
    public string RetryWebCaseFileErrorJob_IsEnabled { get; set; } = null!;

    /// <summary>
    /// 網路件申請書檔案異常重新抓取_執行數量
    /// </summary>
    public int RetryWebCaseFileErrorJob_BatchSize { get; set; }

    /// <summary>
    /// A02KYC同步排程_是否啟動
    /// Y / N
    /// </summary>
    public string A02KYCSyncJob_IsEnabled { get; set; } = null!;

    /// <summary>
    /// A02KYC同步排程_執行數量
    /// </summary>
    public int A02KYCSyncJob_BatchSize { get; set; }

    /// <summary>
    /// 每2小時比對漏進案件批次_是否啟動 
    /// Y / N
    /// </summary>
    public string CompareMissingCases_IsEnabled { get; set; } = null!;

    /// <summary>
    /// 網路進件卡友檢核新案件_是否啟動
    /// Y / N
    /// </summary>
    public string EcardA02CheckNewCase_IsEnabled { get; set; } = null!;

    /// <summary>
    /// 網路進件卡友檢核新案件_執行數量
    /// </summary>
    public int EcardA02CheckNewCase_BatchSize { get; set; }

    /// <summary>
    /// 網路進件非卡友檢核新案件_是否啟動
    /// Y / N
    /// </summary>
    public string EcardNotA02CheckNewCase_IsEnabled { get; set; } = null!;

    /// <summary>
    /// 網路進件非卡友檢核新案件_執行數量
    /// </summary>
    public int EcardNotA02CheckNewCase_BatchSize { get; set; }

    /// <summary>
    /// 國旅卡人士資料檢核排程_是否啟動
    /// Y / N
    /// </summary>
    public string GuoLuKaCheck_IsEnabled { get; set; } = null!;

    /// <summary>
    /// 國旅卡人士資料檢核排程_執行數量
    /// </summary>
    public int GuoLuKaCheck_BatchSize { get; set; }

    /// <summary>
    /// 國旅卡人士資料檢核排程_國旅卡撤件天數
    /// </summary>
    public int GuoLuKaCaseWithdrawDays { get; set; }

    /// <summary>
    /// 紙本件檢核新案件排程_是否啟動
    /// Y / N
    /// </summary>
    public string PaperCheckNewCase_IsEnabled { get; set; } = null!;

    /// <summary>
    /// 紙本件檢核新案件排程_查詢數量
    /// </summary>
    public int PaperCheckNewCase_BatchSize { get; set; }

    /// <summary>
    /// 重試KYC入檔作業排程_是否啟動
    /// Y / N
    /// </summary>
    public string RetryKYCSync_IsEnabled { get; set; } = null!;

    /// <summary>
    /// 重試KYC入檔作業排程數_執行量
    /// </summary>
    public int RetryKYCSync_BatchSize { get; set; }

    /// <summary>
    /// 寄信KYC錯誤_是否啟動
    /// Y / N
    /// </summary>
    public string SendKYCErrorLog_IsEnabled { get; set; } = null!;

    /// <summary>
    /// 寄信KYC錯誤_寄信數量
    /// </summary>
    public int SendKYCErrorLog_BatchSize { get; set; }

    /// <summary>
    /// 寄信系統錯誤_是否啟動
    /// Y / N
    /// </summary>
    public string SendSystemErrorLog_IsEnabled { get; set; } = null!;

    /// <summary>
    /// 寄信系統錯誤_寄信數量
    /// </summary>
    public int SendSystemErrorLog_BatchSize { get; set; }

    /// <summary>
    /// 報表作業補件函批次_是否啟動
    /// Y / N
    /// </summary>
    public string SupplementTemplateReport_IsEnabled { get; set; } = null!;

    /// <summary>
    /// 系統派案_網路件待月收入預審_是否啟動
    /// Y / N
    /// </summary>
    public string SystemAssignment_WebCase_IsEnabled { get; set; } = null!;

    /// <summary>
    /// 系統派案_紙本件待月收入預審_是否啟動
    /// Y / N
    /// </summary>
    public string SystemAssignment_Paper_IsEnabled { get; set; } = null!;

    /// <summary>
    /// 系統派案人工徵信中_是否啟動
    /// Y / N
    /// </summary>
    public string SystemAssignment_ReviewManual_IsEnabled { get; set; } = null!;
}
