// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class System_DeleteLog
{
    /// <summary>
    /// PK
    /// </summary>
    public int SeqNo { get; set; }

    /// <summary>
    /// 刪除資料的資料表名稱
    /// </summary>
    public string TableName { get; set; } = null!;

    /// <summary>
    /// 原始資料，儲存格式為 Json
    /// </summary>
    public string OriginData { get; set; } = null!;

    /// <summary>
    /// 刪除使用者Id
    /// </summary>
    public string DeleteUserId { get; set; } = null!;

    public DateTime DeleteTime { get; set; }
}
