// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace ScoreSharp.API.Infrastructures.Data.Entities
{
    public partial class Usp_GetApplyCreditCardInfoWithParamsResult
    {
        [StringLength(25)]
        public string Type { get; set; } = default!;
        [StringLength(2147483647)]
        public string Name { get; set; } = default!;
        [StringLength(10)]
        public string StringValue { get; set; } = default!;
        public int? IntValue { get; set; }
        [StringLength(1)]
        public string IsActive { get; set; } = default!;
    }
}
