// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class View_WebDigist
{
    public string ApplyNo { get; set; } = null!;

    public string? ID { get; set; }

    public string? CHName { get; set; }

    public CardStatus CardStatus { get; set; }

    public string? CompName { get; set; }

    public string? UserSourceIP { get; set; }

    public DateTime? OTPTime { get; set; }

    public string? OTPMobile { get; set; }

    public string? Mobile { get; set; }

    public string? EMail { get; set; }

    public string? PromotionUnit { get; set; }

    public string? PromotionUser { get; set; }

    public string? SameIP_Flag { get; set; }

    public string? SameIP_IsError { get; set; }

    public string? SameIP_CheckRecord { get; set; }

    public string? SameIP_UpdateUserId { get; set; }

    public DateTime? SameIP_UpdateTime { get; set; }

    public string? SameMobile_Flag { get; set; }

    public string? SameMobile_IsError { get; set; }

    public string? SameMobile_CheckRecord { get; set; }

    public string? SameMobile_UpdateUserId { get; set; }

    public DateTime? SameMobile_UpdateTime { get; set; }

    public string? SameEmail_Flag { get; set; }

    public string? SameEmail_IsError { get; set; }

    public string? SameEmail_CheckRecord { get; set; }

    public string? SameEmail_UpdateUserId { get; set; }

    public DateTime? SameEmail_UpdateTime { get; set; }

    public DateTime ApplyDate { get; set; }
}
