// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class View_ApplicationCategoryJoinCard
{
    public string ApplicationCategoryCode { get; set; } = null!;

    public string ApplicationCategoryName { get; set; } = null!;

    public string IsOCRForm { get; set; } = null!;

    public string IsActive { get; set; } = null!;

    public string AddUserId { get; set; } = null!;

    public DateTime AddTime { get; set; }

    public string? UpdateUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    public string BINCode { get; set; } = null!;

    public string CardName { get; set; } = null!;

    public string CardCode { get; set; } = null!;
}
