// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.Data.Entities;

public partial class View_CardJoinCardPromotion
{
    public string BINCode { get; set; } = null!;

    public string CardCode { get; set; } = null!;

    public string CardName { get; set; } = null!;

    public CardCategory CardCategory { get; set; }

    public SampleRejectionLetter SampleRejectionLetter { get; set; }

    public string DefaultBillDay { get; set; } = null!;

    public SaleLoanCategory SaleLoanCategory { get; set; }

    public string DefaultDiscount { get; set; } = null!;

    public string IsActive { get; set; } = null!;

    public int PrimaryCardQuotaUpperlimit { get; set; }

    public int PrimaryCardQuotaLowerlimit { get; set; }

    public int PrimaryCardYearUpperlimit { get; set; }

    public int PrimaryCardYearLowerlimit { get; set; }

    public int SupplementaryCardQuotaUpperlimit { get; set; }

    public int SupplementaryCardQuotaLowerlimit { get; set; }

    public int SupplementaryCardYearUpperlimit { get; set; }

    public int SupplementaryCardYearLowerlimit { get; set; }

    public string IsCARDPAUnderLimit { get; set; } = null!;

    public int CARDPACQuotaLimit { get; set; }

    public string IsApplyAdditionalCard { get; set; } = null!;

    public string IsIndependentCard { get; set; } = null!;

    public string IsIVRvCTIQuery { get; set; } = null!;

    public string IsCITSCard { get; set; } = null!;

    public string IsQuickCardIssuance { get; set; } = null!;

    public string IsTicket { get; set; } = null!;

    public string IsJointGroup { get; set; } = null!;

    public string AddUserId { get; set; } = null!;

    public DateTime AddTime { get; set; }

    public string? UpdateUserId { get; set; }

    public DateTime? UpdateTime { get; set; }

    public string CardPromotionCode { get; set; } = null!;

    public string CardPromotionName { get; set; } = null!;
}
