// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ScoreSharp.Middleware.Infrastructures.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ScoreSharp.Middleware.Infrastructures.Data
{
    public partial interface IScoreSharpContextProcedures
    {
        Task<List<Usp_GetApplyCreditCardInfoWithParamsResult>> Usp_GetApplyCreditCardInfoWithParamsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
