// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.PaperMiddleware.Infrastructures.Data.Entities;

public partial class Reviewer_ApplyCreditCardInfoFile
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 頁碼
    /// 可以與 Reviewer_ApplyFileLog 與對應
    /// </summary>
    public int Page { get; set; }

    /// <summary>
    /// 狀態或者動作
    /// </summary>
    public string Process { get; set; } = null!;

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 新增員工，系統執行為SYSTEM
    /// </summary>
    public string AddUserId { get; set; } = null!;

    /// <summary>
    /// 備註
    /// </summary>
    public string? Note { get; set; }

    /// <summary>
    /// 檔案 GUID
    /// 
    /// 關聯Reviewer_ApplyFile
    /// </summary>
    public Guid FileId { get; set; }

    /// <summary>
    /// 資料庫檔案名稱
    /// </summary>
    public string DBName { get; set; } = null!;

    /// <summary>
    /// Y/N，預設N
    /// </summary>
    public string IsHistory { get; set; } = null!;
}
