// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.PaperMiddleware.Infrastructures.Data.Entities;

public partial class Reviewer_ApplyCreditCardInfoMain
{
    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 身份證字號
    /// </summary>
    public string? ID { get; set; }

    /// <summary>
    /// 固定 1 = 正卡人
    /// </summary>
    public UserType UserType { get; set; }

    /// <summary>
    /// 中文姓名
    /// </summary>
    public string? CHName { get; set; }

    /// <summary>
    /// 性別：1.男生 2. 女生
    /// </summary>
    public Sex? Sex { get; set; }

    /// <summary>
    /// 生日：民國格式為 YYYMMDD
    /// </summary>
    public string? BirthDay { get; set; }

    /// <summary>
    /// 英文名稱
    /// </summary>
    public string? ENName { get; set; }

    /// <summary>
    /// 身分證發證日期：民國格式為 YYYMMDD
    /// </summary>
    public string? IDIssueDate { get; set; }

    /// <summary>
    /// 身分證發證地點：關聯 SetUp_IDCardRenewalLocation
    /// </summary>
    public string? IDCardRenewalLocationCode { get; set; }

    /// <summary>
    /// 身分證請領狀態：1. 初發, 2. 補發, 3. 換發
    /// </summary>
    public IDTakeStatus? IDTakeStatus { get; set; }

    /// <summary>
    /// 國籍：關聯 SetUp_Citizenship
    /// </summary>
    public string? CitizenshipCode { get; set; }

    /// <summary>
    /// 出生地國籍：1. 中華民國 2. 其他
    /// </summary>
    public BirthCitizenshipCode? BirthCitizenshipCode { get; set; }

    /// <summary>
    /// 出生地其他
    /// 出生地 = 其他為必填
    /// 需符合徵審系統「國籍設定」。
    /// </summary>
    public string? BirthCitizenshipCodeOther { get; set; }

    /// <summary>
    /// 婚姻狀況：1. 已婚, 2. 未婚, 3. 其他
    /// </summary>
    public MarriageState? MarriageState { get; set; }

    /// <summary>
    /// 教育程度：1. 博士, 2. 碩士, 3. 大學, 4. 專科, 5. 高中職, 6. 其他
    /// </summary>
    public Education? Education { get; set; }

    /// <summary>
    /// 畢業國小
    /// </summary>
    public string? GraduatedElementarySchool { get; set; }

    /// <summary>
    /// 行動電話
    /// </summary>
    public string? Mobile { get; set; }

    /// <summary>
    /// E-MAIL
    /// </summary>
    public string? EMail { get; set; }

    /// <summary>
    /// 居住地址類型，主要用於前端顯示
    /// 
    /// 1. 同戶籍地址
    /// 2. 同帳單地址
    /// 3. 同寄卡地址
    /// 4. 同公司地址
    /// 5. 其他
    /// 
    /// </summary>
    public LiveAddressType? LiveAddressType { get; set; }

    /// <summary>
    /// 帳單地址類型
    /// 
    /// 1. 同戶籍地址
    /// 2. 同居住地址
    /// 3. 同寄卡地址
    /// 4. 同公司地址
    /// 5. 其他
    /// 
    /// </summary>
    public BillAddressType? BillAddressType { get; set; }

    /// <summary>
    /// 寄卡地址類型，主要用於前端
    /// 
    /// 1. 同戶籍地址
    /// 2. 同居住地址
    /// 3. 同帳單地址
    /// 4. 同公司地址
    /// 5. 親領
    /// 6. 其他
    /// 
    /// </summary>
    public SendCardAddressType? SendCardAddressType { get; set; }

    /// <summary>
    /// 戶籍電話
    /// 範例020-28572463
    /// 3碼-七八碼
    /// </summary>
    public string? HouseRegPhone { get; set; }

    /// <summary>
    /// 居住電話
    /// 範例020-28572463
    /// 3碼-七八碼
    /// </summary>
    public string? LivePhone { get; set; }

    /// <summary>
    /// 居住地所有權人：1. 本人, 2. 配偶, 3. 父母, 4. 子女, 5. 親戚, 6. 朋友, 7. 其他
    /// </summary>
    public LiveOwner? LiveOwner { get; set; }

    /// <summary>
    /// 居住年數
    /// </summary>
    public int? LiveYear { get; set; }

    /// <summary>
    /// 居留證發證日期 (格式: YYYYMMDD)
    /// </summary>
    public string? ResidencePermitIssueDate { get; set; }

    /// <summary>
    /// 護照號碼
    /// </summary>
    public string? PassportNo { get; set; }

    /// <summary>
    /// 護照日期 (格式: YYYYMMDD)
    /// </summary>
    public string? PassportDate { get; set; }

    /// <summary>
    /// 外籍人士指定效期 (格式: YYYYMM)
    /// </summary>
    public string? ExpatValidityPeriod { get; set; }

    /// <summary>
    /// 是否FATCA身份 (Y/N)，當國籍 = 美國時候預設為 Y
    /// </summary>
    public string? IsFATCAIdentity { get; set; }

    /// <summary>
    /// 社會安全號碼，FATCA身份=Y，徵審人員會去跟客人要此值
    /// </summary>
    public string? SocialSecurityCode { get; set; }

    /// <summary>
    /// 姓名檢核理由代碼，可為複數以「,」分割，敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 要有理由碼
    /// 1. PEP   
    /// 2. 要再問
    /// 3. 黑名單
    /// 4. 負面新聞
    /// 5. 無
    /// 6. RCA
    /// 7. 國內PEP
    /// 8. 國外PEP
    /// 9. 國際組織PEP
    /// 10. 卸任PEP
    /// 
    /// </summary>
    public string? NameCheckedReasonCodes { get; set; }

    /// <summary>
    /// 當前或曾為PEP身分 (Y/N)，敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 需填寫
    /// </summary>
    public string? ISRCAForCurrentPEP { get; set; }

    /// <summary>
    /// 卸任PEP種類：1. 國內 2.國外 3.國際組織 / 敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 需填寫
    /// </summary>
    public ResignPEPKind? ResignPEPKind { get; set; }

    /// <summary>
    /// 擔任PEP範圍:
    /// 不滿2年
    /// 滿兩年但不滿四年
    /// 滿4年 / 敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 需填寫
    /// </summary>
    public PEPRange? PEPRange { get; set; }

    /// <summary>
    /// 現任職位是否與PEP職位相關 (Y/N)，敦陽系統黑名單是否相符= Y 和 姓名檢核 = Y 需填寫
    /// </summary>
    public string? IsCurrentPositionRelatedPEPPosition { get; set; }

    /// <summary>
    /// 公司名稱
    /// </summary>
    public string? CompName { get; set; }

    /// <summary>
    /// 公司統一編號
    /// </summary>
    public string? CompID { get; set; }

    /// <summary>
    /// 公司職稱
    /// </summary>
    public string? CompJobTitle { get; set; }

    /// <summary>
    /// 公司年資
    /// </summary>
    public int? CompSeniority { get; set; }

    /// <summary>
    /// 公司電話
    /// 範例020-28572463#55555
    /// 3碼-七八碼#5碼分機
    /// </summary>
    public string? CompPhone { get; set; }

    /// <summary>
    /// AML職業別：關聯  SetUp_AMLProfession
    /// </summary>
    public string? AMLProfessionCode { get; set; }

    /// <summary>
    /// AML職業別版本、關聯SetUp_AMLProfession
    /// </summary>
    public string? AMLProfessionCode_Version { get; set; }

    /// <summary>
    /// AML職業別_其他
    /// </summary>
    public string? AMLProfessionOther { get; set; }

    /// <summary>
    /// AML職級別：關聯 SetUp_AMLJobLevel
    /// </summary>
    public string? AMLJobLevelCode { get; set; }

    /// <summary>
    /// 公司行業別
    /// 
    /// 金融業 = 1
    /// 公務機關 = 2
    /// 營造/製造/運輸業 =3
    /// 一般商業 = 4
    /// 休閒 / 娛樂 / 服務業 = 5
    /// 軍警消防業 = 6
    /// 非營利團體 = 7
    /// 學生 = 8
    /// 自由業_其他 = 9
    /// 
    /// 
    /// </summary>
    public CompTrade? CompTrade { get; set; }

    /// <summary>
    /// 公司職級別
    /// 
    /// 駕駛人員 = 1
    /// 服務生/門市人員 = 2
    /// 專業人員 = 3
    /// 專業技工 = 4
    /// 業務人員 = 5
    /// 一般職員 = 6
    /// 主管階層 = 7
    /// 股東/董事/負責人 = 8
    /// 家管/其他 = 9
    /// 
    /// 
    /// </summary>
    public CompJobLevel? CompJobLevel { get; set; }

    /// <summary>
    /// 現職月收入(元)
    /// </summary>
    public int? CurrentMonthIncome { get; set; }

    /// <summary>
    /// 所得及資金來源 (請參考Setup_MainIncomeAndFund表格、需符合Paperless「主要所得及資金來源勾選」，多選選項以逗號(,)區隔)
    /// </summary>
    public string? MainIncomeAndFundCodes { get; set; }

    /// <summary>
    /// 主要收入_其他
    /// </summary>
    public string? MainIncomeAndFundOther { get; set; }

    /// <summary>
    /// 是否學生身份 (Y: 是, N: 否)，經審查，有可能從學生改成非學生，也有可能從非學生改成學生。
    /// </summary>
    public string? IsStudent { get; set; }

    /// <summary>
    /// 學生就讀學校 (IsStudent = Y 才有值)
    /// </summary>
    public string? StudSchool { get; set; }

    /// <summary>
    /// 學生預定畢業日期 (IsStudent = Y 才有值, 格式: YYYMMDD)
    /// </summary>
    public string? StudScheduledGraduationDate { get; set; }

    /// <summary>
    /// 家長姓名
    /// </summary>
    public string? ParentName { get; set; }

    /// <summary>
    /// 家長電話
    /// 可以行動電話或者家電或公司電話
    /// 家電範例020-28572463，3碼-七八碼
    /// 公司範例020-28572463#55555，3碼-七八碼#5碼分機
    /// 手機範例0978822811
    /// </summary>
    public string? ParentPhone { get; set; }

    /// <summary>
    /// 家長地址類型
    /// 
    /// 1. 同正卡戶籍地址
    /// 2. 同正卡居住地址
    /// 3. 其他
    /// 
    /// </summary>
    public ParentLiveAddressType? ParentLiveAddressType { get; set; }

    /// <summary>
    /// 學生申請人與本人關係 (1: 父母, 2: 學生)
    /// </summary>
    public StudentApplicantRelationship? StudentApplicantRelationship { get; set; }

    /// <summary>
    /// B68無擔保掛帳金額
    /// </summary>
    public int? B68UnsecuredCreditAmount { get; set; }

    /// <summary>
    /// 本人是否同意提供資料予聯名認同集團 (Y: 是, N: 否)
    /// </summary>
    public string? IsAgreeDataOpen { get; set; }

    /// <summary>
    /// 是否綁定消費通知 (Y: 是, N: 否)
    /// </summary>
    public string? IsPayNoticeBind { get; set; }

    /// <summary>
    /// 是否同意提供資料供本行進行行銷 (Y: 是, N: 否)
    /// </summary>
    public string? IsAgreeMarketing { get; set; }

    /// <summary>
    /// 是否同意悠遊卡自動加值預設設定 (Y: 是, N: 否)
    /// </summary>
    public string? IsAcceptEasyCardDefaultBonus { get; set; }

    /// <summary>
    /// 帳單形式 (1：電子帳單、2：簡訊帳單、3：紙本帳單、4：LINE帳單
    /// )
    /// </summary>
    public BillType? BillType { get; set; }

    /// <summary>
    /// 是否申請自動扣款 (Y: 是, N: 否)
    /// </summary>
    public string? IsApplyAutoDeduction { get; set; }

    /// <summary>
    /// 自動扣繳帳戶-銀行存摺帳號
    /// </summary>
    public string? AutoDeductionBankAccount { get; set; }

    /// <summary>
    /// 自動扣繳帳戶-扣款方式 (10,最低 20,全額)
    /// </summary>
    public AutoDeductionPayType? AutoDeductionPayType { get; set; }

    /// <summary>
    /// 居留證背面號碼：前兩碼大寫英文 + 8 碼數字，範例ＹＺ80000001
    /// </summary>
    public string? ResidencePermitBackendNum { get; set; }

    /// <summary>
    /// 是否為永久居留證
    /// 1. 配合法遵部政策，新增欄位。
    /// 2. 欄位用拉霸方式選擇，Y/N，預設為N。
    /// 3. 如為{N}，則須鍵入外籍人士指定效期。
    /// 
    /// </summary>
    public string? IsForeverResidencePermit { get; set; }

    /// <summary>
    /// 居留證期限：格式 YYYYMMDD
    /// </summary>
    public string? ResidencePermitDeadline { get; set; }

    /// <summary>
    /// 敦陽系統黑名單是否相符（Y：是、N：否）
    /// 由行員確認
    /// </summary>
    public string? IsDunyangBlackList { get; set; }

    /// <summary>
    /// 舊照查驗
    /// Y：是、N：否
    /// </summary>
    public string? OldCertificateVerified { get; set; }

    /// <summary>
    /// 進件方式
    /// 
    /// 1. 親訪親簽
    /// 2. 親訪未見親簽
    /// 3. 設攤親簽
    /// 4. 設為未見親簽
    /// 5. 自來件
    /// 6. 電話行銷
    /// 
    /// </summary>
    public AcceptType? AcceptType { get; set; }

    /// <summary>
    /// 客服備註
    /// </summary>
    public string? CustomerServiceNotes { get; set; }

    /// <summary>
    /// 正附卡
    /// 依客人申請帶出，現網路申請僅能申請正卡
    /// 
    /// 1. 正卡
    /// 2. 附卡
    /// 3. 正卡+附卡
    /// 4. 附卡2
    /// 5. 正卡+附卡2
    /// 
    /// </summary>
    public CardOwner? CardOwner { get; set; }

    /// <summary>
    /// 客戶特殊註記
    /// </summary>
    public string? CustomerSpecialNotes { get; set; }

    /// <summary>
    /// 推廣單位
    /// </summary>
    public string? PromotionUnit { get; set; }

    /// <summary>
    /// 推廣人員
    /// </summary>
    public string? PromotionUser { get; set; }

    /// <summary>
    /// 安麗直銷商編號
    /// </summary>
    public string? AnliNo { get; set; }

    /// <summary>
    /// 專案代號
    /// 
    /// - E-CARD提供
    /// - 得知由文彬組使用，只要來源端提供照存即可
    /// 
    /// </summary>
    public string? ProjectCode { get; set; }

    /// <summary>
    /// 最後處理時間
    /// </summary>
    public DateTime? LastUpdateTime { get; set; }

    /// <summary>
    /// 最後修改資料人員
    /// </summary>
    public string? LastUpdateUserId { get; set; }

    /// <summary>
    /// 來源
    /// E-CARD提供Ecard、APP
    /// 
    /// 1. ECARD
    /// 2. APP
    /// 3. 紙本
    /// </summary>
    public Source Source { get; set; }

    /// <summary>
    /// 申請日期
    /// </summary>
    public DateTime ApplyDate { get; set; }

    /// <summary>
    /// 當前狀態處理經辦
    /// 系統派案指定
    /// 有此員編才能在個人工作清單查到
    /// </summary>
    public string? CurrentHandleUserId { get; set; }

    /// <summary>
    /// 使用者來源IP位置
    /// </summary>
    public string? UserSourceIP { get; set; }

    /// <summary>
    /// OTP時間
    /// </summary>
    public DateTime? OTPTime { get; set; }

    /// <summary>
    /// OTP手機號碼
    /// </summary>
    public string? OTPMobile { get; set; }

    /// <summary>
    /// LineBankUUID
    /// </summary>
    public string? LineBankUUID { get; set; }

    /// <summary>
    /// 是否變更KYC，Y｜N
    /// </summary>
    public string? IsKYCChange { get; set; }

    /// <summary>
    /// Ecard附件註記
    /// 1. 附件異常
    /// 2.  MYDATA後補
    /// </summary>
    public AttachmentNotes? EcardAttachmentNotes { get; set; }

    /// <summary>
    /// MyData案件編號
    /// 當附件註記為2：MYDATA後補時，本欄位必定有值
    /// E-CARD提供
    /// </summary>
    public string? MyDataCaseNo { get; set; }

    /// <summary>
    /// 身份別
    /// 1. 新戶
    /// 2. 原持卡人
    /// 3. 卡友
    /// 4. 存戶
    /// 5. 持他行卡
    /// 6. 自然人憑證
    /// 
    /// E-CARD提供-卡友、存戶、持他行卡、自然人憑證
    /// </summary>
    public IDType? IDType { get; set; }

    /// <summary>
    /// 首刷禮代碼
    /// E-CARD提供
    /// 原系統是使用家庭成員6年齡
    /// </summary>
    public string? FirstBrushingGiftCode { get; set; }

    /// <summary>
    /// 案件種類
    /// 1. 一般件
    /// 2. 急件
    /// 3. 緊急製卡
    /// </summary>
    public CaseType CaseType { get; set; }

    /// <summary>
    /// 申請書ID
    /// E-CARD提供於[eCard_file].[dbo].[ApplyFile]關聯
    /// </summary>
    public string? CardAppId { get; set; }

    /// <summary>
    /// 洗防風險等級：由AML-KYC提供風險等級
    /// </summary>
    public string? AMLRiskLevel { get; set; }

    /// <summary>
    /// 是否申請數位卡(Y：是、N：否)
    /// </summary>
    public string? IsApplyDigtalCard { get; set; }

    /// <summary>
    /// 是否為分行客戶
    /// 
    /// - Y / N
    /// </summary>
    public string? IsBranchCustomer { get; set; }

    /// <summary>
    /// 長循分期戶
    /// 
    /// Y 、N
    /// </summary>
    public string? LongTerm { get; set; }

    /// <summary>
    /// 黑名單註記
    /// 
    /// - 查詢paperless內建資料庫是否有資料相符情形
    /// - Y 、N
    /// - 於月收入確認完進行黑名單查詢
    /// 
    /// </summary>
    public string? BlackListNote { get; set; }

    /// <summary>
    /// 是否原持卡人
    /// - Y:是/N:否
    /// - 查詢 MW3 原持卡人如有資料則為Y則為原持卡人
    /// </summary>
    public string? IsOriginalCardholder { get; set; }

    /// <summary>
    /// 是否重複申請件
    /// - Y:是/N:否
    /// - 查詢 MW3 原持卡人如有資料則為Y且徵審系統有資料則為重複進件
    /// 
    /// </summary>
    public string? IsRepeatApply { get; set; }

    /// <summary>
    /// 是否轉換卡別
    /// Y：是、N：否
    /// 紙本案件，申請書上可幫客人轉換卡別
    /// 對應紙本案件欄位正卡_換發別種卡別
    /// </summary>
    public string? IsConvertCard { get; set; }

    /// <summary>
    /// 前手經辦
    /// 
    /// - 未分案清單+調撥案件時指定
    /// - 用於退回申請時指定人員
    /// 
    /// </summary>
    public string? PreviousHandleUserId { get; set; }

    /// <summary>
    /// 戶籍_郵遞區號
    /// </summary>
    public string? Reg_ZipCode { get; set; }

    /// <summary>
    /// 戶籍_縣市
    /// </summary>
    public string? Reg_City { get; set; }

    /// <summary>
    /// 戶籍_區域
    /// </summary>
    public string? Reg_District { get; set; }

    /// <summary>
    /// 戶籍_路
    /// </summary>
    public string? Reg_Road { get; set; }

    /// <summary>
    /// 戶籍_巷
    /// </summary>
    public string? Reg_Lane { get; set; }

    /// <summary>
    /// 戶籍_弄
    /// </summary>
    public string? Reg_Alley { get; set; }

    /// <summary>
    /// 戶籍_號
    /// </summary>
    public string? Reg_Number { get; set; }

    /// <summary>
    /// 戶籍_之號
    /// </summary>
    public string? Reg_SubNumber { get; set; }

    /// <summary>
    /// 戶籍_樓層
    /// </summary>
    public string? Reg_Floor { get; set; }

    /// <summary>
    /// 戶籍_完整地址
    /// </summary>
    public string? Reg_FullAddr { get; set; }

    /// <summary>
    /// 戶籍_其他
    /// </summary>
    public string? Reg_Other { get; set; }

    /// <summary>
    /// 居住_郵遞區號
    /// </summary>
    public string? Live_ZipCode { get; set; }

    /// <summary>
    /// 居住_縣市
    /// </summary>
    public string? Live_City { get; set; }

    /// <summary>
    /// 居住_區域
    /// </summary>
    public string? Live_District { get; set; }

    /// <summary>
    /// 居住_街道
    /// </summary>
    public string? Live_Road { get; set; }

    /// <summary>
    /// 居住_巷
    /// </summary>
    public string? Live_Lane { get; set; }

    /// <summary>
    /// 居住_弄
    /// </summary>
    public string? Live_Alley { get; set; }

    /// <summary>
    /// 居住_號
    /// </summary>
    public string? Live_Number { get; set; }

    /// <summary>
    /// 居住_之號
    /// </summary>
    public string? Live_SubNumber { get; set; }

    /// <summary>
    /// 居住_樓層
    /// </summary>
    public string? Live_Floor { get; set; }

    /// <summary>
    /// 居住_完整地址
    /// </summary>
    public string? Live_FullAddr { get; set; }

    /// <summary>
    /// 居住_其他
    /// </summary>
    public string? Live_Other { get; set; }

    /// <summary>
    /// 公司_郵遞區號
    /// </summary>
    public string? Comp_ZipCode { get; set; }

    /// <summary>
    /// 公司_縣市
    /// </summary>
    public string? Comp_City { get; set; }

    /// <summary>
    /// 公司_區域
    /// </summary>
    public string? Comp_District { get; set; }

    /// <summary>
    /// 公司_街道
    /// </summary>
    public string? Comp_Road { get; set; }

    /// <summary>
    /// 公司_巷
    /// </summary>
    public string? Comp_Lane { get; set; }

    /// <summary>
    /// 公司_弄
    /// </summary>
    public string? Comp_Alley { get; set; }

    /// <summary>
    /// 公司_號
    /// </summary>
    public string? Comp_Number { get; set; }

    /// <summary>
    /// 公司_之號
    /// </summary>
    public string? Comp_SubNumber { get; set; }

    /// <summary>
    /// 公司_樓層
    /// </summary>
    public string? Comp_Floor { get; set; }

    /// <summary>
    /// 公司_完整地址
    /// </summary>
    public string? Comp_FullAddr { get; set; }

    /// <summary>
    /// 公司_其他
    /// </summary>
    public string? Comp_Other { get; set; }

    /// <summary>
    /// 家長_郵遞區號
    /// </summary>
    public string? ParentLive_ZipCode { get; set; }

    /// <summary>
    /// 家長_縣市
    /// </summary>
    public string? ParentLive_City { get; set; }

    /// <summary>
    /// 家長_區域
    /// </summary>
    public string? ParentLive_District { get; set; }

    /// <summary>
    /// 家長_路
    /// </summary>
    public string? ParentLive_Road { get; set; }

    /// <summary>
    /// 家長_巷
    /// </summary>
    public string? ParentLive_Lane { get; set; }

    /// <summary>
    /// 家長_弄
    /// </summary>
    public string? ParentLive_Alley { get; set; }

    /// <summary>
    /// 家長_號
    /// </summary>
    public string? ParentLive_Number { get; set; }

    /// <summary>
    /// 家長_之號
    /// </summary>
    public string? ParentLive_SubNumber { get; set; }

    /// <summary>
    /// 家長_樓層
    /// </summary>
    public string? ParentLive_Floor { get; set; }

    /// <summary>
    /// 家長_完整地址
    /// </summary>
    public string? ParentLive_FullAddr { get; set; }

    /// <summary>
    /// 家長_其他
    /// </summary>
    public string? ParentLive_Other { get; set; }

    /// <summary>
    /// 寄卡_郵遞區號
    /// </summary>
    public string? SendCard_ZipCode { get; set; }

    /// <summary>
    /// 寄卡_縣市
    /// </summary>
    public string? SendCard_City { get; set; }

    /// <summary>
    /// 寄卡_區域
    /// </summary>
    public string? SendCard_District { get; set; }

    /// <summary>
    /// 寄卡_街道
    /// </summary>
    public string? SendCard_Road { get; set; }

    /// <summary>
    /// 寄卡_巷
    /// </summary>
    public string? SendCard_Lane { get; set; }

    /// <summary>
    /// 寄卡_弄
    /// </summary>
    public string? SendCard_Alley { get; set; }

    /// <summary>
    /// 寄卡_號
    /// </summary>
    public string? SendCard_Number { get; set; }

    /// <summary>
    /// 寄卡_之號
    /// </summary>
    public string? SendCard_SubNumber { get; set; }

    /// <summary>
    /// 寄卡_樓層
    /// </summary>
    public string? SendCard_Floor { get; set; }

    /// <summary>
    /// 寄卡_完整地址
    /// </summary>
    public string? SendCard_FullAddr { get; set; }

    /// <summary>
    /// 寄卡_其他
    /// </summary>
    public string? SendCard_Other { get; set; }

    /// <summary>
    /// 帳單_郵遞區號
    /// </summary>
    public string? Bill_ZipCode { get; set; }

    /// <summary>
    /// 帳單_縣市
    /// </summary>
    public string? Bill_City { get; set; }

    /// <summary>
    /// 帳單_區域
    /// </summary>
    public string? Bill_District { get; set; }

    /// <summary>
    /// 帳單_路
    /// </summary>
    public string? Bill_Road { get; set; }

    /// <summary>
    /// 帳單_巷
    /// </summary>
    public string? Bill_Lane { get; set; }

    /// <summary>
    /// 帳單_弄
    /// </summary>
    public string? Bill_Alley { get; set; }

    /// <summary>
    /// 帳單_號
    /// </summary>
    public string? Bill_Number { get; set; }

    /// <summary>
    /// 帳單_之號
    /// </summary>
    public string? Bill_SubNumber { get; set; }

    /// <summary>
    /// 帳單_樓層
    /// </summary>
    public string? Bill_Floor { get; set; }

    /// <summary>
    /// 帳單_完整地址
    /// </summary>
    public string? Bill_FullAddr { get; set; }

    /// <summary>
    /// 帳單_其他
    /// </summary>
    public string? Bill_Other { get; set; }

    /// <summary>
    /// Y/N，預設N
    /// </summary>
    public string IsHistory { get; set; } = null!;

    /// <summary>
    /// 子女人數
    /// </summary>
    public int? ChildrenCount { get; set; }

    /// <summary>
    /// 部門名稱
    /// 【商務卡】及【國旅卡】的紙本申請書有此欄位，新徵審系統需增加此欄位，欄位位置規劃中
    /// 自行填寫
    /// </summary>
    public string? DepartmentName { get; set; }

    /// <summary>
    /// 到職日期
    /// 民國年 1090101
    /// </summary>
    public string? EmploymentDate { get; set; }

    /// <summary>
    /// 電子化約定條款
    /// 範例：202007
    /// </summary>
    public string? ElecCodeId { get; set; }

    /// <summary>
    /// 是否持有本行卡
    /// Y 、N
    /// </summary>
    public string? IsHoldingBankCard { get; set; }

    /// <summary>
    /// 年費收取方式
    /// 關聯SetUp_AnnualFeeCollectionMethod 年費收取方式設定
    /// </summary>
    public string? AnnualFeePaymentType { get; set; }

    /// <summary>
    /// 姓名檢核
    /// 
    /// - 敦陽系統之姓名檢核
    /// - Y 、N
    /// </summary>
    public string? NameChecked { get; set; }

    /// <summary>
    /// ECard申請書附件是否異常
    /// Y 、N
    /// 紙本件固定為Null
    /// 原卡友會固定N
    /// </summary>
    public string? ECard_AppendixIsException { get; set; }
}
