// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.PaperMiddleware.Infrastructures.Data.Entities;

public partial class Reviewer_ApplyCreditCardInfoProcess
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 案件狀態跟執行動作
    /// </summary>
    public string Process { get; set; } = null!;

    /// <summary>
    /// 開始時間
    /// </summary>
    public DateTime StartTime { get; set; }

    /// <summary>
    /// 結束時間
    /// </summary>
    public DateTime EndTime { get; set; }

    /// <summary>
    /// 備註
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// 處理人員
    /// 系統人員 =  SYSTEM
    /// </summary>
    public string? ProcessUserId { get; set; }
}
