// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

public partial class Reviewer3rd_929Log
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 交易日期
    /// </summary>
    public string? TxnDate { get; set; }

    /// <summary>
    /// 歸屬分行
    /// </summary>
    public string? BrachCode { get; set; }

    /// <summary>
    /// 交易櫃員
    /// </summary>
    public string? BrachEmp { get; set; }

    /// <summary>
    /// 業務來源
    /// </summary>
    public string? BusinessCode { get; set; }

    /// <summary>
    /// 戶名
    /// </summary>
    public string? ChName { get; set; }

    /// <summary>
    /// 登錄日期
    /// </summary>
    public string? LoginDate { get; set; }

    /// <summary>
    /// 拒絕原因
    /// </summary>
    public string? ApplyCause { get; set; }

    /// <summary>
    /// 備註
    /// </summary>
    public string? ApplyReMark { get; set; }

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 使用者類型
    /// 
    /// 1. 正卡人
    /// 2. 附卡人
    /// </summary>
    public UserType UserType { get; set; }
}
