// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

public partial class Reviewer_OutsideBankInfo
{
    /// <summary>
    /// 申請書編號，PK
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 身分證字號，PK
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 活存目前餘額
    /// </summary>
    public int? HUOCUN_Balance { get; set; }

    /// <summary>
    /// 定存目前餘額
    /// </summary>
    public int? DINGCUN_Balance { get; set; }

    /// <summary>
    /// 活存90天平均餘額
    /// </summary>
    public int? HUOCUN_Balance_90 { get; set; }

    /// <summary>
    /// 定存90天平均餘額
    /// </summary>
    public int? DINGCUN_Balance_90 { get; set; }

    /// <summary>
    /// 餘額更新日期
    /// </summary>
    public DateTime? BalanceUpdateDate { get; set; }

    /// <summary>
    /// 使用者類型，PK
    /// 1.正卡人
    /// 2.附卡人
    /// </summary>
    public int UserType { get; set; }
}
