// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

/// <summary>
/// 受警示企業戶之負責人Log
/// </summary>
public partial class Reviewer3rd_WarnCompLog
{
    /// <summary>
    /// PK，自增
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 帳號
    /// </summary>
    public string? Account { get; set; }

    /// <summary>
    /// 公司統編
    /// 統編+A
    /// </summary>
    public string? CorporateID { get; set; }

    /// <summary>
    /// 企業戶負責人ID
    /// ID+A
    /// </summary>
    public string? PID { get; set; }

    /// <summary>
    /// 開戶日期，八碼
    /// </summary>
    public string? AccountDate { get; set; }

    /// <summary>
    /// 事故代號
    /// 29：受警示之人 39：延伸之人 00：刪除名單
    /// </summary>
    public string? AccidentCode { get; set; }

    /// <summary>
    /// 事故設定日期
    /// </summary>
    public string? AccidentDate { get; set; }

    /// <summary>
    /// 事故解除日期
    /// </summary>
    public string? AccidentCancelDate { get; set; }

    /// <summary>
    /// 資料更新日期
    /// </summary>
    public string? CreateDate { get; set; }

    /// <summary>
    /// 使用者類型
    /// 1. 正卡人
    /// 2. 附卡人
    /// </summary>
    public UserType UserType { get; set; }

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;
}
