// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

public partial class Reviewer3rd_LayOffLog
{
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 使用者類型
    /// </summary>
    public UserType UserType { get; set; }

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 傳輸日期
    /// </summary>
    public string? TransDate { get; set; }

    /// <summary>
    /// 異動代碼
    /// 
    /// I = 新增
    /// U = 修改
    /// D = 刪除
    /// </summary>
    public string? ChngId { get; set; }

    /// <summary>
    /// 國籍代碼
    /// </summary>
    public string? NatCode { get; set; }

    /// <summary>
    /// 護照號碼
    /// </summary>
    public string? PassNo { get; set; }

    /// <summary>
    /// 撤銷函文號
    /// </summary>
    public string? ExpirWkNo { get; set; }

    /// <summary>
    /// 雇主通報日期
    /// </summary>
    public string? KnowDate { get; set; }

    /// <summary>
    /// 移工解聘日期
    /// </summary>
    public string? DynaDate { get; set; }

    /// <summary>
    /// 狀況代碼
    /// </summary>
    public string? HappCode { get; set; }

    /// <summary>
    /// 雇主處分代碼
    /// </summary>
    public string? VendCode { get; set; }

    /// <summary>
    /// 外國人處分代碼
    /// </summary>
    public string? LaborCode { get; set; }

    /// <summary>
    /// 撤銷函日期
    /// </summary>
    public string? ExpireDate { get; set; }

    /// <summary>
    /// 打詐通報種類代碼
    /// </summary>
    public string? ImmiType { get; set; }

    /// <summary>
    /// 打詐通報種類代碼中文說明
    /// </summary>
    public string? ImmiTypeDesc { get; set; }

    /// <summary>
    /// 狀況代碼中文說明
    /// </summary>
    public string? HappCodeDesc { get; set; }

    /// <summary>
    /// 雇主處分代碼中文說明
    /// </summary>
    public string? VendCodeDesc { get; set; }

    /// <summary>
    /// 外國人處分代碼中文說明
    /// </summary>
    public string? LaborCodeDesc { get; set; }

    /// <summary>
    /// 定型搞代碼
    /// </summary>
    public string? WpCode { get; set; }

    /// <summary>
    /// 定型搞代碼中文說明
    /// </summary>
    public string? WpCodeDesc { get; set; }

    /// <summary>
    /// 勞發署居留證號
    /// </summary>
    public string? Resnum { get; set; }

    /// <summary>
    /// 居留截止日
    /// </summary>
    public string? ImmigartionDate { get; set; }

    /// <summary>
    /// 移民署傳檔日
    /// </summary>
    public string? SystemDate { get; set; }

    /// <summary>
    /// 移民署居留證號
    /// </summary>
    public string? NiaResidenceNo { get; set; }

    /// <summary>
    /// 資料更新日期
    /// </summary>
    public string? CreateDate { get; set; }
}
