// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

public partial class Reviewer_CheckTrace
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 現行申請書編號 
    /// 
    /// - FK 
    /// - 非叢集索引
    /// </summary>
    public string CurrentApplyNo { get; set; } = null!;

    /// <summary>
    /// 同ID之申請書編號
    /// </summary>
    public string SameApplyNo { get; set; } = null!;

    /// <summary>
    /// 現行身分證字號
    /// </summary>
    public string CurrentID { get; set; } = null!;

    /// <summary>
    /// 使用者類型 
    /// 
    /// 1. 正卡人
    /// 2. 附卡人
    /// </summary>
    public UserType CurrentUserType { get; set; }

    /// <summary>
    /// 檢核類型 
    /// 
    /// 1. 相同IP比對
    /// 2. 網路件 EMAIL 比對
    /// 3. 網路件手機號碼比對
    /// 4. 短時間頻繁ID比對
    /// </summary>
    public CheckTraceType CheckType { get; set; }
}
