// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

public partial class ReviewerPedding_WebRetryCase
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// Request
    /// </summary>
    public string Request { get; set; } = null!;

    /// <summary>
    /// 回應代碼
    /// </summary>
    public string ReturnCode { get; set; } = null!;

    /// <summary>
    /// 回應代碼
    /// 
    /// 當以下代碼會由資訊人員重新發送
    /// 0005
    /// 0006
    /// 0007
    /// 
    /// 
    /// </summary>
    public string CaseErrorLog { get; set; } = null!;

    /// <summary>
    /// 最後寄送員工
    /// </summary>
    public string? LastSendUserId { get; set; }

    /// <summary>
    /// 最後寄送時間
    /// </summary>
    public DateTime? LastSendTtime { get; set; }

    /// <summary>
    /// 是否寄送
    /// </summary>
    public string IsSend { get; set; } = null!;

    public DateTime AddTime { get; set; }
}
