// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

public partial class Reviewer3rd_KYCQueryLog
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 卡片狀態
    /// 
    /// 當下卡片狀態，已「/」分割
    /// 例: 完成月收入確認/待月收入預審
    /// </summary>
    public string CardStatus { get; set; } = null!;

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// Request
    /// </summary>
    public string Request { get; set; } = null!;

    /// <summary>
    /// KYC Code
    /// </summary>
    public string KYCCode { get; set; } = null!;

    /// <summary>
    /// KYC等級
    /// </summary>
    public string KYCRank { get; set; } = null!;

    /// <summary>
    /// KYC 訊息
    /// </summary>
    public string KYCMsg { get; set; } = null!;

    /// <summary>
    /// Response
    /// </summary>
    public string Response { get; set; } = null!;

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// KYC最後發送狀態
    /// </summary>
    public KYCLastSendStatus KYCLastSendStatus { get; set; }

    /// <summary>
    /// KYC最後寄送時間
    /// </summary>
    public DateTime? KYCLastSendTime { get; set; }

    /// <summary>
    /// 當前經辦
    /// 
    /// - 如果為排程執行，請填是哪個排程
    /// </summary>
    public string CurrentHandler { get; set; } = null!;

    /// <summary>
    /// API 類型
    /// 
    /// - 範例 KYC00SECREDIT
    /// </summary>
    public string APIName { get; set; } = null!;

    /// <summary>
    /// 來源
    /// </summary>
    public string Source { get; set; } = null!;
}
