// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

public partial class Reviewer3rd_BranchCusCusInfo
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 識別碼
    /// 
    /// 支票平均存款近6個月平均餘額均達10萬元以上,
    /// 房屋貸款客戶-排除逾期繳款,
    /// 薪轉戶,
    /// 財富管理戶-尊榮級,
    /// 財富管理戶-潛力級
    /// </summary>
    public string SN { get; set; } = null!;

    /// <summary>
    /// 分行代碼
    /// </summary>
    public string Cate { get; set; } = null!;

    /// <summary>
    /// 使用者類型
    /// 
    /// 1. 正卡人
    /// 2. 附卡人
    /// </summary>
    public UserType UserType { get; set; }
}
