// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

public partial class Reviewer3rd_BranchCusCD
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 幣別
    /// 
    /// 範例: TWD
    /// </summary>
    public string Currency { get; set; } = null!;

    /// <summary>
    /// 起息日
    /// 
    /// 範例: 01000101
    /// </summary>
    public string InterestD { get; set; } = null!;

    /// <summary>
    /// 降息日
    /// 
    /// 範例: 01000101
    /// </summary>
    public string ExpirationD { get; set; } = null!;

    /// <summary>
    /// 金額
    /// </summary>
    public int Amount { get; set; }

    /// <summary>
    /// 分行代碼
    /// </summary>
    public string Cate { get; set; } = null!;

    /// <summary>
    /// 使用者類型
    /// </summary>
    public UserType UserType { get; set; }
}
