// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

public partial class ReviewerLog_GuoLuKaCheckFail
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// 
    /// 非叢集索引
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 回覆
    /// </summary>
    public string? Response { get; set; }

    /// <summary>
    /// 建立日期
    /// </summary>
    public DateTime CreateTime { get; set; }

    /// <summary>
    /// 寄信狀態
    /// </summary>
    public SendStatus SendStatus { get; set; }

    /// <summary>
    /// 發送時間
    /// </summary>
    public DateTime? SendTime { get; set; }

    /// <summary>
    /// 錯誤訊息
    /// </summary>
    public string? SendFailLog { get; set; }
}
