// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

public partial class Reviewer3rd_FrdIdLog
{
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 使用者類型
    /// </summary>
    public UserType UserType { get; set; }

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 帳號
    /// </summary>
    public string? Account { get; set; }

    /// <summary>
    /// 通報日期
    /// </summary>
    public string? NotifyDate { get; set; }

    /// <summary>
    /// 資料更新日期
    /// </summary>
    public string? CreateDate { get; set; }
}
