// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

/// <summary>
/// 系統參數設定
/// </summary>
public partial class SysParamManage_SysParam
{
    /// <summary>
    /// PK
    /// </summary>
    public int SeqNo { get; set; }

    /// <summary>
    /// IP比對時間(小時)
    /// </summary>
    public int IPCompareHour { get; set; }

    /// <summary>
    /// IP比對吻合次數
    /// </summary>
    public int IPMatchCount { get; set; }

    /// <summary>
    /// 往前推歷史資料幾天
    /// </summary>
    public int QueryHisDataDayRange { get; set; }

    /// <summary>
    /// 網路件相同EMail比對時間(小時)
    /// </summary>
    public int WebCaseEmailCompareHour { get; set; }

    /// <summary>
    /// 網路件相同EMail比對吻合次數
    /// </summary>
    public int WebCaseEmailMatchCount { get; set; }

    /// <summary>
    /// 網路件相同手機比對時間(小時)
    /// </summary>
    public int WebCaseMobileCompareHour { get; set; }

    /// <summary>
    /// 網路件相同手機比對吻合次數
    /// </summary>
    public int WebCaseMobileMatchCount { get; set; }

    /// <summary>
    /// 短時間ID比對時間(小時)
    /// </summary>
    public int ShortTimeIDCompareHour { get; set; }

    /// <summary>
    /// 短時間ID比對吻合次數
    /// </summary>
    public int ShortTimeIDMatchCount { get; set; }

    /// <summary>
    /// AML職業別版本
    /// 利用此版本對應 AML職業別
    /// 關聯SetUp_AMLProfession
    /// </summary>
    public string AMLProfessionCode_Version { get; set; } = null!;

    /// <summary>
    /// KYC 維護開始時間
    /// </summary>
    public DateTime? KYCFixStartTime { get; set; }

    /// <summary>
    /// KYC 維護結束時間
    /// </summary>
    public DateTime? KYCFixEndTime { get; set; }

    /// <summary>
    /// KYC加強審核版本
    /// 
    /// - 利用此欄位決定KYC加強審核版本主要用於套印加強審核檔案
    /// - 關聯 Reviewer_FinanceCheckInfo
    /// 
    /// 
    /// </summary>
    public string KYC_StrongReVersion { get; set; } = null!;
}
