// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

public partial class SysParamManage_MailSet
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 系統錯誤_郵件樣板
    /// 
    /// 範例 Email/EmailTemplate
    /// </summary>
    public string SystemErrorLog_Template { get; set; } = null!;

    /// <summary>
    /// 系統錯誤_郵收件人
    /// 
    /// 以逗點分割
    /// </summary>
    public string SystemErrorLog_To { get; set; } = null!;

    /// <summary>
    /// 系統錯誤_郵收件標題
    /// </summary>
    public string SystemErrorLog_Title { get; set; } = null!;

    /// <summary>
    /// 國旅卡客戶檢核失敗_郵件樣板
    /// </summary>
    public string GuoLuKaCheckFailLog_Template { get; set; } = null!;

    /// <summary>
    /// 國旅卡客戶檢核失敗_收件人
    /// </summary>
    public string GuoLuKaCheckFailLog_To { get; set; } = null!;

    /// <summary>
    /// 國旅卡客戶檢核失敗_收件標題
    /// </summary>
    public string GuoLuKaCheckFailLog_Title { get; set; } = null!;

    /// <summary>
    /// KYC錯誤_郵件樣板
    /// </summary>
    public string KYCErrorLog_Template { get; set; } = null!;

    /// <summary>
    /// KYC錯誤_收件人
    /// </summary>
    public string KYCErrorLog_To { get; set; } = null!;

    /// <summary>
    /// KYC錯誤_收件標題
    /// </summary>
    public string KYCErrorLog_Title { get; set; } = null!;
}
