// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Batch.Infrastructures.Data.Entities;

public partial class System_TmpRecord
{
    /// <summary>
    /// PK
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 系統派案_網路件預審最後派案人員
    /// </summary>
    public string? SystemAssignment_WebCaseLastUserId { get; set; }

    /// <summary>
    /// 系統派案_紙本件預審最後派案人員
    /// </summary>
    public string? SystemAssignment_PaperCaseLastUserId { get; set; }

    /// <summary>
    /// 系統派案_人工徵信件最後派案人員
    /// </summary>
    public string? SystemAssignment_ManualCaseLastUserId { get; set; }
}
