// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.API.Infrastructures.FileData.Entities;

public partial class Reviewer_ApplyFile
{
    public long SeqNo { get; set; }

    /// <summary>
    /// FileTable 所需
    /// </summary>
    public Guid FileId { get; set; }

    /// <summary>
    /// 申請書編號
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 檔案名稱
    /// 
    /// - 包含附檔名
    /// - 申請書編號_檔案類型_時間戳_副檔名
    /// 
    /// </summary>
    public string FileName { get; set; } = null!;

    /// <summary>
    /// 檔案內容
    /// </summary>
    public byte[] FileContent { get; set; } = null!;

    /// <summary>
    /// 檔案類型
    /// 
    /// 1. 申請書相關
    /// 2. 行員附件
    /// 
    /// </summary>
    public FileType FileType { get; set; }
}
