// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ScoreSharp.PaperMiddleware.Infrastructures.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ScoreSharp.PaperMiddleware.Infrastructures.Data
{
    public partial class ScoreSharpContext
    {
        private IScoreSharpContextProcedures _procedures;

        public virtual IScoreSharpContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ScoreSharpContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IScoreSharpContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class ScoreSharpContextProcedures : IScoreSharpContextProcedures
    {
        private readonly ScoreSharpContext _context;

        public ScoreSharpContextProcedures(ScoreSharpContext context)
        {
            _context = context;
        }

        public virtual async Task<List<Usp_GetApplyCreditCardInfoWithParamsResult>> Usp_GetApplyCreditCardInfoWithParamsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Usp_GetApplyCreditCardInfoWithParamsResult>("EXEC @returnValue = [dbo].[Usp_GetApplyCreditCardInfoWithParams]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
