//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreSharp.Middleware.Infrastructures.ValidationMessage {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMetadataMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMetadataMessage() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScoreSharp.Middleware.Infrastructures.ValidationMessage.ValidationMetadataMessage" +
                            "", typeof(ValidationMetadataMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位 不是正確的信用卡卡號格式。 的當地語系化字串。
        /// </summary>
        internal static string CreditCardAttribute_Invalid {
            get {
                return ResourceManager.GetString("CreditCardAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位 的資料不正確。 的當地語系化字串。
        /// </summary>
        internal static string CustomValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位 不是正確的Email格式。 的當地語系化字串。
        /// </summary>
        internal static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位 只接受副檔名為: {1} 的檔案。 的當地語系化字串。
        /// </summary>
        internal static string FileExtensionsAttribute_Invalid {
            get {
                return ResourceManager.GetString("FileExtensionsAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位 字元長度最多為 {1} 個。 的當地語系化字串。
        /// </summary>
        internal static string MaxLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位 字元長度最少為 {1} 個。 的當地語系化字串。
        /// </summary>
        internal static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位 不是正確的電話號碼格式。 的當地語系化字串。
        /// </summary>
        internal static string PhoneAttribute_Invalid {
            get {
                return ResourceManager.GetString("PhoneAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位 必須介在 {1} 跟 {2} 之間。 的當地語系化字串。
        /// </summary>
        internal static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位 不符合正規表式 &apos;{1}&apos;。 的當地語系化字串。
        /// </summary>
        internal static string RegularExpressionAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位為必填。 的當地語系化字串。
        /// </summary>
        internal static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位 字元長度最多為 {1} 個。 的當地語系化字串。
        /// </summary>
        internal static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位 字元長度必須在 {2} 跟 {1} 之間。 的當地語系化字串。
        /// </summary>
        internal static string StringLengthAttribute_ValidationErrorIncludingMinimum {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationErrorIncludingMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位 不是正確的 HTTP, HTTPS, 或 FTP 網址。 的當地語系化字串。
        /// </summary>
        internal static string UrlAttribute_Invalid {
            get {
                return ResourceManager.GetString("UrlAttribute_Invalid", resourceCulture);
            }
        }
    }
}
