// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Middleware.Infrastructures.Data.Entities;

/// <summary>
/// 卡別紀錄
/// </summary>
public partial class Reviewer_CardRecord
{
    /// <summary>
    /// PK
    /// 自增
    /// </summary>
    public long SeqNo { get; set; }

    /// <summary>
    /// 申請書編號
    /// 非叢集索引
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 卡片狀態
    /// </summary>
    public CardStatus CardStatus { get; set; }

    /// <summary>
    /// 核卡額度
    /// </summary>
    public int? CardLimit { get; set; }

    /// <summary>
    /// 核准員工
    /// </summary>
    public string ApproveUserId { get; set; } = null!;

    /// <summary>
    /// 新增時間
    /// </summary>
    public DateTime AddTime { get; set; }

    /// <summary>
    /// 處理備註
    /// </summary>
    public string? HandleNote { get; set; }

    /// <summary>
    /// FK
    /// 關聯 Reviewer_ApplyCreditCardInfoHandle
    /// ULID
    /// </summary>
    public string HandleSeqNo { get; set; } = null!;

    /// <summary>
    /// 轉交員工
    /// 當執行權限外時會出現此值，被轉交員工會掛於此
    /// </summary>
    public string? ForwardedToUserId { get; set; }

    /// <summary>
    /// 執行動作
    /// 1.權限內
    /// 2.權限外 (轉交)
    /// 3.退回重審
    /// </summary>
    public ExecutionAction? Action { get; set; }
}
