// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Middleware.Infrastructures.Data.Entities;

public partial class Reviewer_ApplyCreditCardInfoHandle
{
    /// <summary>
    /// PK
    /// ULID
    /// </summary>
    public string SeqNo { get; set; } = null!;

    /// <summary>
    /// 申請書編號
    /// 
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 使用者類型
    /// 1 = 正卡人 
    /// 2 =  附卡人
    /// </summary>
    public UserType UserType { get; set; }

    /// <summary>
    /// 卡片狀態，查看附件-卡片狀態碼
    /// </summary>
    public CardStatus CardStatus { get; set; }

    /// <summary>
    /// 徵信代碼
    /// 1. 當前最新徵信代碼
    /// 2. 關聯 SetUp_CreditCheckCode
    /// 3. 提供進行月收入確認時使用，是否僅能在月收入確認
    /// </summary>
    public string? CreditCheckCode { get; set; }

    /// <summary>
    /// 申請卡別：以&apos;/&apos;串接，如JA00/JC00，關聯　SetUp_Card
    /// </summary>
    public string ApplyCardType { get; set; } = null!;

    /// <summary>
    /// 審查人員編號
    /// 
    /// - 未完成案件於人工徵審派案的第一手權限內人員
    /// - 調撥案件或派案時更改
    /// - 審查人員皆相同
    /// 
    /// </summary>
    public string? ReviewerUserId { get; set; }

    /// <summary>
    /// 核准人員員編
    /// 
    /// - 案件最終的核准人員，如案件為系統核准，核准人員為SYSTEM
    /// - 核件、退件、撤件最後押上
    /// - 核准人員在多張卡片會不同
    /// 
    /// </summary>
    public string? ApproveUserId { get; set; }

    /// <summary>
    /// 申請卡種 ( 1: 實體, 2: 數位, 3: 實體+數位)
    /// </summary>
    public ApplyCardKind? ApplyCardKind { get; set; }

    /// <summary>
    /// 月收入確認人員
    /// 
    /// - 完成月收入確認時更改,沒有點完全月收入確認就不用
    /// - 完成月收入確認人員皆相同
    /// </summary>
    public string? MonthlyIncomeCheckUserId { get; set; }

    /// <summary>
    /// 案件異動動作
    /// 權限內
    ///  1.補件
    ///  2.撤件
    ///  3.退件
    ///  4.核卡 (人工徵信中才有)
    /// 權限外 (人工徵信中才有)
    ///  5.排入補件
    ///  6.排入撤件
    ///  7.排入退件
    ///  8.排入核卡
    /// 
    /// </summary>
    public CaseChangeAction? CaseChangeAction { get; set; }

    /// <summary>
    /// 補件原因代碼
    /// 關聯 SetUp_SupplementReason
    /// </summary>
    public string? SupplementReasonCode { get; set; }

    /// <summary>
    /// 其他補件原因
    /// </summary>
    public string? OtherSupplementReason { get; set; }

    /// <summary>
    /// 補件註記
    /// </summary>
    public string? SupplementNote { get; set; }

    /// <summary>
    /// 補件寄送地址
    /// 1. 帳單地址
    /// 2. 戶籍地址
    /// 3. 公司地址
    /// 4. 居住地址
    /// 需檢驗選擇的地址完整性
    /// 查看 Reviewer_ApplyCreditCardInfoAddress 完整地址
    /// </summary>
    public MailingAddressType? SupplementSendCardAddr { get; set; }

    /// <summary>
    /// 撤件註記
    /// </summary>
    public string? WithdrawalNote { get; set; }

    /// <summary>
    /// 退件原因代碼
    /// 關聯 SetUp_RejectionReason
    /// </summary>
    public string? RejectionReasonCode { get; set; }

    /// <summary>
    /// 其他退件原因
    /// </summary>
    public string? OtherRejectionReason { get; set; }

    /// <summary>
    /// 退件註記
    /// </summary>
    public string? RejectionNote { get; set; }

    /// <summary>
    /// 退件寄送地址
    /// 1. 帳單地址
    /// 2. 戶籍地址
    /// 3. 公司地址
    /// 4. 居住地址
    /// 需檢驗選擇的地址完整性
    /// 查看 Reviewer_ApplyCreditCardInfoAddress 完整地址
    /// </summary>
    public MailingAddressType? RejectionSendCardAddr { get; set; }

    /// <summary>
    /// 優惠辦法代碼
    /// </summary>
    public string? CardPromotionCode { get; set; }

    /// <summary>
    /// 是否列印簡訊、紙本通知函，Y｜N
    /// </summary>
    public string? IsPrintSMSAndPaper { get; set; }

    /// <summary>
    /// 核卡額度
    /// </summary>
    public int? CardLimit { get; set; }

    /// <summary>
    /// 原持卡人JCIC補充註記
    /// 
    /// - 現由文彬依聯徵查回結果提供
    /// - Y 、N
    /// </summary>
    public string? OriginCardholderJCICNotes { get; set; }

    /// <summary>
    /// 評分結果
    /// 
    /// - 授信政策科
    /// - 舊系統有*不用這個
    /// 
    /// </summary>
    public int? CreditLimit_RatingAdvice { get; set; }

    /// <summary>
    /// 排程_補件報表狀態
    /// 
    /// - Y (完成)、N (等待)
    /// - Null 代表未要執行 
    /// 
    /// </summary>
    public string? BatchSupplementStatus { get; set; }

    /// <summary>
    /// 排程_補件報表時間
    /// </summary>
    public DateTime? BatchSupplementTime { get; set; }

    /// <summary>
    /// 卡片階段
    /// 1.月收入確認
    /// 2.人工徵審
    /// </summary>
    public CardStep? CardStep { get; set; }

    /// <summary>
    /// 建議額度與原持卡人額度相同
    /// Y / N
    /// </summary>
    public string? IsOriginCardholderSameCardLimit { get; set; }

    /// <summary>
    /// 是否強制發卡
    /// Y / N
    /// </summary>
    public string? IsForceCard { get; set; }

    /// <summary>
    /// 核卡註記
    /// </summary>
    public string? NuclearCardNote { get; set; }

    /// <summary>
    /// 處理備註
    /// </summary>
    public string? HandleNote { get; set; }

    /// <summary>
    /// 排程_退件報表狀態
    /// Y (完成)、N (等待)
    /// Null 代表未要執行 
    /// </summary>
    public string? BatchRejectionStatus { get; set; }

    /// <summary>
    /// 排程_退件報表時間
    /// </summary>
    public DateTime? BatchRejectiontTime { get; set; }

    /// <summary>
    /// 審查時間
    /// </summary>
    public DateTime? ReviewerTime { get; set; }

    /// <summary>
    /// 核准時間
    /// 
    /// - 執行核退撤時間
    /// </summary>
    public DateTime? ApproveTime { get; set; }

    /// <summary>
    /// 月收入確認時間
    /// </summary>
    public DateTime? MonthlyIncomeTime { get; set; }
}
