// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ScoreSharp.Middleware.Infrastructures.Data.Entities;

/// <summary>
/// 徵審_銀行追蹤
/// </summary>
public partial class Reviewer_BankTrace
{
    /// <summary>
    /// 申請書編號，PK
    /// </summary>
    public string ApplyNo { get; set; } = null!;

    /// <summary>
    /// 身分證字號，PK
    /// </summary>
    public string ID { get; set; } = null!;

    /// <summary>
    /// 使用者類型，PK
    /// 1. 正卡人
    /// 2. 附卡人
    /// 
    /// </summary>
    public UserType UserType { get; set; }

    /// <summary>
    /// 行內IP相同，Y｜N
    /// </summary>
    public string? EqualInternalIP_Flag { get; set; }

    /// <summary>
    /// 確認紀錄
    /// 於月收入確認簽核時，當 EqualInternalIP_Flag =Y，需填寫原因
    /// </summary>
    public string? EqualInternalIP_CheckRecord { get; set; }

    /// <summary>
    /// 確認人員
    /// </summary>
    public string? EqualInternalIP_UpdateUserId { get; set; }

    /// <summary>
    /// 確認時間
    /// </summary>
    public DateTime? EqualInternalIP_UpdateTime { get; set; }

    /// <summary>
    /// 是否異常，Y｜N
    /// </summary>
    public string? EqualInternalIP_IsError { get; set; }

    /// <summary>
    /// 相同IP比對，Y｜N
    /// </summary>
    public string? SameIP_Flag { get; set; }

    /// <summary>
    /// 確認紀錄
    /// 於月收入確認簽核時，當 SameIP_Flag =Y，需填寫原因
    /// </summary>
    public string? SameIP_CheckRecord { get; set; }

    /// <summary>
    /// 確認人員
    /// </summary>
    public string? SameIP_UpdateUserId { get; set; }

    /// <summary>
    /// 確認時間
    /// </summary>
    public DateTime? SameIP_UpdateTime { get; set; }

    /// <summary>
    /// IP是否異常，Y｜N
    /// </summary>
    public string? SameIP_IsError { get; set; }

    /// <summary>
    /// 電子信箱是否相同，Y｜N
    /// </summary>
    public string? SameEmail_Flag { get; set; }

    /// <summary>
    /// 電子信箱確認紀錄
    /// 於月收入確認簽核時，當 SameEmail_Falg =Y，需填寫原因
    /// </summary>
    public string? SameEmail_CheckRecord { get; set; }

    /// <summary>
    /// 電子信箱確認人員
    /// </summary>
    public string? SameEmail_UpdateUserId { get; set; }

    /// <summary>
    /// 電子信箱確認時間
    /// </summary>
    public DateTime? SameEmail_UpdateTime { get; set; }

    /// <summary>
    /// 電子信箱是否異常，Y｜N
    /// </summary>
    public string? SameEmail_IsError { get; set; }

    /// <summary>
    /// 電話是否相同，Y｜N
    /// </summary>
    public string? SameMobile_Flag { get; set; }

    /// <summary>
    /// 電話確認紀錄
    /// 於月收入確認簽核時，當 SameMobile_Flag =Y，需填寫原因
    /// </summary>
    public string? SameMobile_CheckRecord { get; set; }

    /// <summary>
    /// 電話確認人員
    /// </summary>
    public string? SameMobile_UpdateUserId { get; set; }

    /// <summary>
    /// 電話確認時間
    /// </summary>
    public DateTime? SameMobile_UpdateTime { get; set; }

    /// <summary>
    /// 電話是否異常，Y｜N
    /// </summary>
    public string? SameMobile_IsError { get; set; }

    /// <summary>
    /// 短時間ID頻繁申請相同
    /// Y/N
    /// 於進件時檢核，當 ShortTimeID_Flag =Y，在執行系統審查時會直接進入人工審核，需填寫原因
    /// </summary>
    public string? ShortTimeID_Flag { get; set; }

    /// <summary>
    /// 短時間ID頻繁_確認紀錄
    /// ShortTimeID_Flag =Y，需填寫原因
    /// </summary>
    public string? ShortTimeID_CheckRecord { get; set; }

    /// <summary>
    /// 短時間ID頻繁_確認人員
    /// </summary>
    public string? ShortTimeID_UpdateUserId { get; set; }

    /// <summary>
    /// 短時間ID頻繁_確認時間
    /// </summary>
    public DateTime? ShortTimeID_UpdateTime { get; set; }

    /// <summary>
    /// 短時間ID頻繁_是否異常
    /// Y/N
    /// InternalEmailSame_Flag =Y，需填寫是否異常
    /// </summary>
    public string? ShortTimeID_IsError { get; set; }

    /// <summary>
    /// 行內Email相同
    /// Y/N
    /// 於進件時檢核，當 InternalEmailSame_Flag =Y，在執行系統審查時會直接進入人工審核，需填寫原因
    /// </summary>
    public string? InternalEmailSame_Flag { get; set; }

    /// <summary>
    /// 行內Email相同_確認紀錄
    /// InternalEmailSame_Flag =Y，需填寫原因
    /// </summary>
    public string? InternalEmailSame_CheckRecord { get; set; }

    /// <summary>
    /// 行內Email相同_確認人員
    /// </summary>
    public string? InternalEmailSame_UpdateUserId { get; set; }

    /// <summary>
    /// 行內Email相同_確認時間
    /// </summary>
    public DateTime? InternalEmailSame_UpdateTime { get; set; }

    /// <summary>
    /// 行內Email相同_是否異常
    /// Y/N
    /// InternalEmailSame_Flag =Y，需填寫是否異常
    /// </summary>
    public string? InternalEmailSame_IsError { get; set; }

    /// <summary>
    /// 行內手機相同
    /// Y/N
    /// 於進件時檢核，當 InternalMobileSame_Flag =Y，在執行系統審查時會直接進入人工審核，需填寫原因
    /// </summary>
    public string? InternalMobileSame_Flag { get; set; }

    /// <summary>
    /// 行內手機相同_確認紀錄
    /// InternalMobileSame_Flag =Y，需填寫原因
    /// </summary>
    public string? InternalMobileSame_CheckRecord { get; set; }

    /// <summary>
    /// 行內手機相同_確認人員
    /// </summary>
    public string? InternalMobileSame_UpdateUserId { get; set; }

    /// <summary>
    /// 行內手機相同_確認時間
    /// </summary>
    public DateTime? InternalMobileSame_UpdateTime { get; set; }

    /// <summary>
    /// 行內手機相同_是否異常
    /// Y/N
    /// InternalMobileSame_Flag =Y，需填寫是否異常
    /// </summary>
    public string? InternalMobileSame_IsError { get; set; }

    /// <summary>
    /// 行內Email相同_確認關係
    /// 1.  父母
    /// 2. 子女
    /// 3. 配偶
    /// 4. 兄弟姊妹
    /// 5. 配偶父母
    /// 6. 其他關係
    /// 7. 無關係
    /// </summary>
    public int? InternalEmailSame_Relation { get; set; }

    /// <summary>
    /// 行內手機相同_確認關係
    /// 1.  父母
    /// 2. 子女
    /// 3. 配偶
    /// 4. 兄弟姊妹
    /// 5. 配偶父母
    /// 6. 其他關係
    /// 7. 無關係
    /// </summary>
    public int? InternalMobileSame_Relation { get; set; }
}
